const kpi_data = {
  1951850: {
    businessUnitsName: "EXP00-HEAD OFFICE",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "EXP00 HEAD OFFICE",
  },
  1951978: {
    businessUnitsName: "EXP01-ADMIN/OFFICE",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "EXP01-ADMINISTRATION/OFFICE",
  },
  1952362: {
    businessUnitsName: "EXP02-WAREHOUSE",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "EXP02-WAREHOUSE",
  },
  1952106: {
    businessUnitsName: "EXP03-SHEET METAL SHOP",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "EXP03-SHEET METAL SHOP",
  },
  1952234: {
    businessUnitsName: "EXP04-FACILITY/BLDG",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "EXP04-FACILITY/BLDG",
  },
  1034878: {
    businessUnitsName: "30EXP-Comm AOR",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "Expert Commercial AOR",
  },
  1034884: {
    businessUnitsName: "90EXP-Comm Maint",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "Expert Commercial Maintenance",
  },
  1034879: {
    businessUnitsName: "40EXP-Comm NC",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "Expert Commercial New Constr",
  },
  1034881: {
    businessUnitsName: "60EXP-Comm Service",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "COMM",
    officialName: "Expert Commercial Service",
  },
  1034882: {
    businessUnitsName: "70EXP-OTC",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "COMM",
    officialName: "Expert Over the Counter",
  },
  1034876: {
    businessUnitsName: "10EXP-Resid AOR",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Expert Residential AOR",
  },
  55793158: {
    businessUnitsName: "11EST-Resid AOR",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Expert Residential AOR",
  },
  1034883: {
    businessUnitsName: "80EXP-Resid Maint",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Expert Residential Maintenance",
  },
  55794188: {
    businessUnitsName: "81EST-Resid Maint",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Expert Residential Maintenance",
  },
  1034877: {
    businessUnitsName: "20EXP-Resid NC",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Expert Residential New Const",
  },
  1034880: {
    businessUnitsName: "50EXP-Resid Service",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "RES",
    officialName: "Expert Residential Service",
  },
  55786506: {
    businessUnitsName: "51EST-Resid Service",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "RES",
    officialName: "Expert Residential Service",
  },
  108709: {
    businessUnitsName: "Imported Default Businessunit",
    tradeType: "HIS",
    revenueType: "HIS",
    accountType: "HIS",
    officialName: "Expert Imported Default Business Unit",
  },
  1000004: {
    businessUnitsName: "Imported Businessunit",
    tradeType: "HIS",
    revenueType: "HIS",
    accountType: "HIS",
    officialName: "Expert Imported Default Business Unit",
  },
  898: {
    businessUnitsName: "GRE HVAC AOR RES",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  899: {
    businessUnitsName: "GRE HVAC MNT COM",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  112805: {
    businessUnitsName: "GRE HVAC AOR COM",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  9722674: {
    businessUnitsName: "GRE HVAC AOR MFY",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074086: {
    businessUnitsName: "GRE HVAC MNT MFY",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074087: {
    businessUnitsName: "GRE HVAC MNT RES",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074088: {
    businessUnitsName: "GRE HVAC NCO COM",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074089: {
    businessUnitsName: "GRE HVAC NCO MFY",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074090: {
    businessUnitsName: "GRE HVAC NCO RES",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074091: {
    businessUnitsName: "GRE HVAC SRV COM",
    tradeType: "HVAC",
    revenueType: "SRV",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074092: {
    businessUnitsName: "GRE HVAC SRV MFY",
    tradeType: "HVAC",
    revenueType: "SRV",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074093: {
    businessUnitsName: "GRE HVAC SRV RES",
    tradeType: "HVAC",
    revenueType: "SRV",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074094: {
    businessUnitsName: "GRE OTHR AOR COM",
    tradeType: "OTHR",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074095: {
    businessUnitsName: "GRE OTHR AOR MFY",
    tradeType: "OTHR",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074096: {
    businessUnitsName: "GRE OTHR AOR RES",
    tradeType: "OTHR",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074097: {
    businessUnitsName: "GRE OTHR MNT COM",
    tradeType: "OTHR",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074098: {
    businessUnitsName: "GRE OTHR MNT MFY",
    tradeType: "OTHR",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074099: {
    businessUnitsName: "GRE OTHR MNT RES",
    tradeType: "OTHR",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074100: {
    businessUnitsName: "GRE OTHR NCO COM",
    tradeType: "OTHR",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074101: {
    businessUnitsName: "GRE OTHR NCO MFY",
    tradeType: "OTHR",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074102: {
    businessUnitsName: "GRE OTHR NCO RES",
    tradeType: "OTHR",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074103: {
    businessUnitsName: "GRE OTHR SRV COM",
    tradeType: "OTHR",
    revenueType: "SRV",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074104: {
    businessUnitsName: "GRE OTHR SRV MFY",
    tradeType: "OTHR",
    revenueType: "SRV",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074105: {
    businessUnitsName: "GRE OTHR SRV RES",
    tradeType: "OTHR",
    revenueType: "SRV",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074106: {
    businessUnitsName: "GRE PLUM AOR COM",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074107: {
    businessUnitsName: "GRE PLUM AOR MFY",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074108: {
    businessUnitsName: "GRE PLUM AOR RES",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074109: {
    businessUnitsName: "GRE PLUM MNT COM",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074110: {
    businessUnitsName: "GRE PLUM MNT MFY",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074111: {
    businessUnitsName: "GRE PLUM MNT RES",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074112: {
    businessUnitsName: "GRE PLUM NCO COM",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074113: {
    businessUnitsName: "GRE PLUM NCO MFY",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074114: {
    businessUnitsName: "GRE PLUM NCO RES",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074115: {
    businessUnitsName: "GRE PLUM SRV COM",
    tradeType: "PLUM",
    revenueType: "SRV",
    accountType: "COMM",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074116: {
    businessUnitsName: "GRE PLUM SRV MFY",
    tradeType: "PLUM",
    revenueType: "SRV",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074117: {
    businessUnitsName: "GRE PLUM SRV RES",
    tradeType: "PLUM",
    revenueType: "SRV",
    accountType: "RES",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  35405856: {
    businessUnitsName: "GRE ADMN GEN OFF",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  51353626: {
    businessUnitsName: "FHC ADMN GEN OFF",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "Family Headquarters",
  },
  13107277: {
    businessUnitsName: "FAM PLUM SRV COM",
    tradeType: "PLUM",
    revenueType: "SER",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating",
  },
  13107279: {
    businessUnitsName: "FAM PLUM SRV RES",
    tradeType: "PLUM",
    revenueType: "SER",
    accountType: "RES",
    officialName: "Family Plumbing & Heating",
  },
  11152547: {
    businessUnitsName: "FAM HVAC AOR COM",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating",
  },
  13107264: {
    businessUnitsName: "FAM HVAC AOR RES",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Family Plumbing & Heating",
  },
  13107265: {
    businessUnitsName: "FAM HVAC MNT COM",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating",
  },
  13107267: {
    businessUnitsName: "FAM HVAC MNT RES",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Family Plumbing & Heating",
  },
  13107268: {
    businessUnitsName: "FAM HVAC SRV COM",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating",
  },
  13107270: {
    businessUnitsName: "FAM HVAC SRV RES",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "RES",
    officialName: "Family Plumbing & Heating",
  },
  13107271: {
    businessUnitsName: "FAM PLUM AOR COM",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating",
  },
  13107273: {
    businessUnitsName: "FAM PLUM AOR RES",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Family Plumbing & Heating",
  },
  13107274: {
    businessUnitsName: "FAM PLUM MNT COM",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating",
  },
  13107276: {
    businessUnitsName: "FAM PLUM MNT RES",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Family Plumbing & Heating",
  },
  16118462: {
    businessUnitsName: "FAM ADMN GEN OFF",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "Family Plumbing & Heating",
  },
  16118463: {
    businessUnitsName: "FAM HVAC NCO COM",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating",
  },
  16118464: {
    businessUnitsName: "FAM HVAC NCO RES",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Family Plumbing & Heating",
  },
  16118465: {
    businessUnitsName: "FAM PLUM NCO COM",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating",
  },
  16118466: {
    businessUnitsName: "FAM PLUM NCO RES",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Family Plumbing & Heating",
  },
  11156773: {
    businessUnitsName: "SPR HVAC AOR COM",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating North",
  },
  13107306: {
    businessUnitsName: "SPR HVAC AOR RES",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Family Plumbing & Heating North",
  },
  13107307: {
    businessUnitsName: "SPR HVAC MNT COM",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating North",
  },
  13107309: {
    businessUnitsName: "SPR HVAC MNT RES",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Family Plumbing & Heating North",
  },
  13107310: {
    businessUnitsName: "SPR HVAC SRV COM",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating North",
  },
  13107312: {
    businessUnitsName: "SPR HVAC SRV RES",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "RES",
    officialName: "Family Plumbing & Heating North",
  },
  13107313: {
    businessUnitsName: "SPR PLUM AOR COM",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating North",
  },
  13107315: {
    businessUnitsName: "SPR PLUM AOR RES",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Family Plumbing & Heating North",
  },
  13107316: {
    businessUnitsName: "SPR PLUM MNT COM",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating North",
  },
  13107318: {
    businessUnitsName: "SPR PLUM MNT RES",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Family Plumbing & Heating North",
  },
  13107319: {
    businessUnitsName: "SPR PLUM SRV COM",
    tradeType: "PLUM",
    revenueType: "SER",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating North",
  },
  13107321: {
    businessUnitsName: "SPR PLUM SRV RES",
    tradeType: "PLUM",
    revenueType: "SER",
    accountType: "RES",
    officialName: "Family Plumbing & Heating North",
  },
  16118485: {
    businessUnitsName: "SPR ADMN GEN OFF",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "Family Plumbing & Heating North",
  },
  16118486: {
    businessUnitsName: "SPR HVAC NCO COM",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating North",
  },
  16118487: {
    businessUnitsName: "SPR HVAC NCO RES",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Family Plumbing & Heating North",
  },
  16118488: {
    businessUnitsName: "SPR PLUM NCO COM",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "Family Plumbing & Heating North",
  },
  16118489: {
    businessUnitsName: "SPR PLUM NCO RES",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Family Plumbing & Heating North",
  },
  11156642: {
    businessUnitsName: "HAN HVAC AOR COM",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "Hank's Heating & Cooling",
  },
  13107281: {
    businessUnitsName: "HAN HVAC AOR RES",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Hank's Heating & Cooling",
  },
  13107282: {
    businessUnitsName: "HAN HVAC MNT COM",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "Hank's Heating & Cooling",
  },
  13107284: {
    businessUnitsName: "HAN HVAC MNT RES",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Hank's Heating & Cooling",
  },
  13107285: {
    businessUnitsName: "HAN HVAC SRV COM",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "COMM",
    officialName: "Hank's Heating & Cooling",
  },
  13107287: {
    businessUnitsName: "HAN HVAC SRV RES",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "RES",
    officialName: "Hank's Heating & Cooling",
  },
  13107288: {
    businessUnitsName: "HAN PLUM AOR COM",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "Hank's Heating & Cooling",
  },
  13107290: {
    businessUnitsName: "HAN PLUM AOR RES",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "Hank's Heating & Cooling",
  },
  13107291: {
    businessUnitsName: "HAN PLUM MNT COM",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "Hank's Heating & Cooling",
  },
  13107293: {
    businessUnitsName: "HAN PLUM MNT RES",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "Hank's Heating & Cooling",
  },
  13107294: {
    businessUnitsName: "HAN PLUM SRV COM",
    tradeType: "PLUM",
    revenueType: "SER",
    accountType: "COMM",
    officialName: "Hank's Heating & Cooling",
  },
  13107296: {
    businessUnitsName: "HAN PLUM SRV RES",
    tradeType: "PLUM",
    revenueType: "SER",
    accountType: "RES",
    officialName: "Hank's Heating & Cooling",
  },
  16118467: {
    businessUnitsName: "HAN ADMN GEN OFF",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "Hank's Heating & Cooling",
  },
  16118468: {
    businessUnitsName: "HAN HVAC NCO COM",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "Hank's Heating & Cooling",
  },
  16118469: {
    businessUnitsName: "HAN HVAC NCO RES",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Hank's Heating & Cooling",
  },
  16118470: {
    businessUnitsName: "HAN PLUM NCO COM",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "Hank's Heating & Cooling",
  },
  16118471: {
    businessUnitsName: "HAN PLUM NCO RES",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "Hank's Heating & Cooling",
  },
  166181: {
    businessUnitsName: "Imported Default Businessunit",
    tradeType: "HIS",
    revenueType: "HIS",
    accountType: "HIS",
    officialName: "Family Imported Default Business Unit",
  },
  11157153: {
    businessUnitsName: "KNL HVAC NCO COM",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "K&L Plumbing and Heating",
  },
  13107298: {
    businessUnitsName: "KNL HVAC NCO RES",
    tradeType: "HVAC",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "K&L Plumbing and Heating",
  },
  13107302: {
    businessUnitsName: "KNL PLUM NCO COM",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "COMM",
    officialName: "K&L Plumbing and Heating",
  },
  13107304: {
    businessUnitsName: "KNL PLUM NCO RES",
    tradeType: "PLUM",
    revenueType: "NCO",
    accountType: "RES",
    officialName: "K&L Plumbing and Heating",
  },
  16118472: {
    businessUnitsName: "KNL ADMN GEN OFF",
    tradeType: "EXP",
    revenueType: "EXP",
    accountType: "EXP",
    officialName: "K&L Plumbing and Heating",
  },
  16118473: {
    businessUnitsName: "KNL HVAC AOR COM",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "K&L Plumbing and Heating",
  },
  16118474: {
    businessUnitsName: "KNL HVAC AOR RES",
    tradeType: "HVAC",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "K&L Plumbing and Heating",
  },
  16118475: {
    businessUnitsName: "KNL HVAC MNT COM",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "K&L Plumbing and Heating",
  },
  16118476: {
    businessUnitsName: "KNL HVAC MNT RES",
    tradeType: "HVAC",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "K&L Plumbing and Heating",
  },
  16118477: {
    businessUnitsName: "KNL HVAC SRV COM",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "COMM",
    officialName: "K&L Plumbing and Heating",
  },
  16118478: {
    businessUnitsName: "KNL HVAC SRV RES",
    tradeType: "HVAC",
    revenueType: "SER",
    accountType: "RES",
    officialName: "K&L Plumbing and Heating",
  },
  16118479: {
    businessUnitsName: "KNL PLUM AOR COM",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "COMM",
    officialName: "K&L Plumbing and Heating",
  },
  16118480: {
    businessUnitsName: "KNL PLUM AOR RES",
    tradeType: "PLUM",
    revenueType: "AOR",
    accountType: "RES",
    officialName: "K&L Plumbing and Heating",
  },
  16118481: {
    businessUnitsName: "KNL PLUM MNT COM",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "COMM",
    officialName: "K&L Plumbing and Heating",
  },
  16118482: {
    businessUnitsName: "KNL PLUM MNT RES",
    tradeType: "PLUM",
    revenueType: "MNT",
    accountType: "RES",
    officialName: "K&L Plumbing and Heating",
  },
  16118483: {
    businessUnitsName: "KNL PLUM SRV COM",
    tradeType: "PLUM",
    revenueType: "SER",
    accountType: "COMM",
    officialName: "K&L Plumbing and Heating",
  },
  16118484: {
    businessUnitsName: "KNL PLUM SRV RES",
    tradeType: "PLUM",
    revenueType: "SER",
    accountType: "RES",
    officialName: "K&L Plumbing and Heating",
  },
};

module.exports = kpi_data;
