const kpi_data = {
  898: {
    "BU ID": 898,
    "Business Units Name": "GRE HVAC AOR RES",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  899: {
    "BU ID": 899,
    "Business Units Name": "GRE HVAC MNT COM",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  108709: {
    "BU ID": 108709,
    "Business Units Name": "Imported Default Businessunit",
    "Account Type": "HIS",
    "Revenue Type": "HIS",
    "Trade Type": "HIS",
  },
  112805: {
    "BU ID": 112805,
    "Business Units Name": "GRE HVAC AOR COM",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  166181: {
    "BU ID": 166181,
    "Business Units Name": "Imported Default Businessunit",
    "Account Type": "HIS",
    "Revenue Type": "HIS",
    "Trade Type": "HIS",
  },
  1000004: {
    "BU ID": 1000004,
    "Business Units Name": "Imported Businessunit",
    "Account Type": "HIS",
    "Revenue Type": "HIS",
    "Trade Type": "HIS",
  },
  1034876: {
    "BU ID": 1034876,
    "Business Units Name": "10EXP-Resid AOR",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  1034877: {
    "BU ID": 1034877,
    "Business Units Name": "20EXP-Resid NC",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  1034878: {
    "BU ID": 1034878,
    "Business Units Name": "30EXP-Comm AOR",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  1034879: {
    "BU ID": 1034879,
    "Business Units Name": "40EXP-Comm NC",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  1034880: {
    "BU ID": 1034880,
    "Business Units Name": "50EXP-Resid Service",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  1034881: {
    "BU ID": 1034881,
    "Business Units Name": "60EXP-Comm Service",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  1034882: {
    "BU ID": 1034882,
    "Business Units Name": "70EXP-OTC",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  1034883: {
    "BU ID": 1034883,
    "Business Units Name": "80EXP-Resid Maint",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  1034884: {
    "BU ID": 1034884,
    "Business Units Name": "90EXP-Comm Maint",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  1951850: {
    "BU ID": 1951850,
    "Business Units Name": "EXP00-HEAD OFFICE",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  1951978: {
    "BU ID": 1951978,
    "Business Units Name": "EXP01-ADMIN/OFFICE",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  1952106: {
    "BU ID": 1952106,
    "Business Units Name": "EXP03-SHEET METAL SHOP",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  1952234: {
    "BU ID": 1952234,
    "Business Units Name": "EXP04-FACILITY/BLDG",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  1952362: {
    "BU ID": 1952362,
    "Business Units Name": "EXP02-WAREHOUSE",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  9722674: {
    "BU ID": 9722674,
    "Business Units Name": "GRE HVAC AOR MFY",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  11152547: {
    "BU ID": 11152547,
    "Business Units Name": "FAM HVAC AOR COM",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  11156642: {
    "BU ID": 11156642,
    "Business Units Name": "HAN HVAC AOR COM",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  11156773: {
    "BU ID": 11156773,
    "Business Units Name": "SPR HVAC AOR COM",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  11157153: {
    "BU ID": 11157153,
    "Business Units Name": "KNL HVAC NCO COM",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  13107264: {
    "BU ID": 13107264,
    "Business Units Name": "FAM HVAC AOR RES",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  13107265: {
    "BU ID": 13107265,
    "Business Units Name": "FAM HVAC MNT COM",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  13107267: {
    "BU ID": 13107267,
    "Business Units Name": "FAM HVAC MNT RES",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  13107268: {
    "BU ID": 13107268,
    "Business Units Name": "FAM HVAC SRV COM",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  13107270: {
    "BU ID": 13107270,
    "Business Units Name": "FAM HVAC SRV RES",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  13107271: {
    "BU ID": 13107271,
    "Business Units Name": "FAM PLUM AOR COM",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  13107273: {
    "BU ID": 13107273,
    "Business Units Name": "FAM PLUM AOR RES",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  13107274: {
    "BU ID": 13107274,
    "Business Units Name": "FAM PLUM MNT COM",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  13107276: {
    "BU ID": 13107276,
    "Business Units Name": "FAM PLUM MNT RES",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  13107277: {
    "BU ID": 13107277,
    "Business Units Name": "FAM PLUM SRV COM",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  13107279: {
    "BU ID": 13107279,
    "Business Units Name": "FAM PLUM SRV RES",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  13107281: {
    "BU ID": 13107281,
    "Business Units Name": "HAN HVAC AOR RES",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  13107282: {
    "BU ID": 13107282,
    "Business Units Name": "HAN HVAC MNT COM",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  13107284: {
    "BU ID": 13107284,
    "Business Units Name": "HAN HVAC MNT RES",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  13107285: {
    "BU ID": 13107285,
    "Business Units Name": "HAN HVAC SRV COM",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  13107287: {
    "BU ID": 13107287,
    "Business Units Name": "HAN HVAC SRV RES",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  13107288: {
    "BU ID": 13107288,
    "Business Units Name": "HAN PLUM AOR COM",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  13107290: {
    "BU ID": 13107290,
    "Business Units Name": "HAN PLUM AOR RES",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  13107291: {
    "BU ID": 13107291,
    "Business Units Name": "HAN PLUM MNT COM",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  13107293: {
    "BU ID": 13107293,
    "Business Units Name": "HAN PLUM MNT RES",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  13107294: {
    "BU ID": 13107294,
    "Business Units Name": "HAN PLUM SRV COM",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  13107296: {
    "BU ID": 13107296,
    "Business Units Name": "HAN PLUM SRV RES",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  13107298: {
    "BU ID": 13107298,
    "Business Units Name": "KNL HVAC NCO RES",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  13107302: {
    "BU ID": 13107302,
    "Business Units Name": "KNL PLUM NCO COM",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  13107304: {
    "BU ID": 13107304,
    "Business Units Name": "KNL PLUM NCO RES",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  13107306: {
    "BU ID": 13107306,
    "Business Units Name": "SPR HVAC AOR RES",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  13107307: {
    "BU ID": 13107307,
    "Business Units Name": "SPR HVAC MNT COM",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  13107309: {
    "BU ID": 13107309,
    "Business Units Name": "SPR HVAC MNT RES",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  13107310: {
    "BU ID": 13107310,
    "Business Units Name": "SPR HVAC SRV COM",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  13107312: {
    "BU ID": 13107312,
    "Business Units Name": "SPR HVAC SRV RES",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  13107313: {
    "BU ID": 13107313,
    "Business Units Name": "SPR PLUM AOR COM",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  13107315: {
    "BU ID": 13107315,
    "Business Units Name": "SPR PLUM AOR RES",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  13107316: {
    "BU ID": 13107316,
    "Business Units Name": "SPR PLUM MNT COM",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  13107318: {
    "BU ID": 13107318,
    "Business Units Name": "SPR PLUM MNT RES",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  13107319: {
    "BU ID": 13107319,
    "Business Units Name": "SPR PLUM SRV COM",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  13107321: {
    "BU ID": 13107321,
    "Business Units Name": "SPR PLUM SRV RES",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  16118462: {
    "BU ID": 16118462,
    "Business Units Name": "FAM ADMN GEN OFF",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  16118463: {
    "BU ID": 16118463,
    "Business Units Name": "FAM HVAC NCO COM",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  16118464: {
    "BU ID": 16118464,
    "Business Units Name": "FAM HVAC NCO RES",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  16118465: {
    "BU ID": 16118465,
    "Business Units Name": "FAM PLUM NCO COM",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  16118466: {
    "BU ID": 16118466,
    "Business Units Name": "FAM PLUM NCO RES",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  16118467: {
    "BU ID": 16118467,
    "Business Units Name": "HAN ADMN GEN OFF",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  16118468: {
    "BU ID": 16118468,
    "Business Units Name": "HAN HVAC NCO COM",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  16118469: {
    "BU ID": 16118469,
    "Business Units Name": "HAN HVAC NCO RES",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  16118470: {
    "BU ID": 16118470,
    "Business Units Name": "HAN PLUM NCO COM",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  16118471: {
    "BU ID": 16118471,
    "Business Units Name": "HAN PLUM NCO RES",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  16118472: {
    "BU ID": 16118472,
    "Business Units Name": "KNL ADMN GEN OFF",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  16118473: {
    "BU ID": 16118473,
    "Business Units Name": "KNL HVAC AOR COM",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  16118474: {
    "BU ID": 16118474,
    "Business Units Name": "KNL HVAC AOR RES",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  16118475: {
    "BU ID": 16118475,
    "Business Units Name": "KNL HVAC MNT COM",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  16118476: {
    "BU ID": 16118476,
    "Business Units Name": "KNL HVAC MNT RES",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  16118477: {
    "BU ID": 16118477,
    "Business Units Name": "KNL HVAC SRV COM",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  16118478: {
    "BU ID": 16118478,
    "Business Units Name": "KNL HVAC SRV RES",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  16118479: {
    "BU ID": 16118479,
    "Business Units Name": "KNL PLUM AOR COM",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  16118480: {
    "BU ID": 16118480,
    "Business Units Name": "KNL PLUM AOR RES",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  16118481: {
    "BU ID": 16118481,
    "Business Units Name": "KNL PLUM MNT COM",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  16118482: {
    "BU ID": 16118482,
    "Business Units Name": "KNL PLUM MNT RES",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  16118483: {
    "BU ID": 16118483,
    "Business Units Name": "KNL PLUM SRV COM",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  16118484: {
    "BU ID": 16118484,
    "Business Units Name": "KNL PLUM SRV RES",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  16118485: {
    "BU ID": 16118485,
    "Business Units Name": "SPR ADMN GEN OFF",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  16118486: {
    "BU ID": 16118486,
    "Business Units Name": "SPR HVAC NCO COM",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  16118487: {
    "BU ID": 16118487,
    "Business Units Name": "SPR HVAC NCO RES",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  16118488: {
    "BU ID": 16118488,
    "Business Units Name": "SPR PLUM NCO COM",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  16118489: {
    "BU ID": 16118489,
    "Business Units Name": "SPR PLUM NCO RES",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  17074086: {
    "BU ID": 17074086,
    "Business Units Name": "GRE HVAC MNT MFY",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  17074087: {
    "BU ID": 17074087,
    "Business Units Name": "GRE HVAC MNT RES",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  17074088: {
    "BU ID": 17074088,
    "Business Units Name": "GRE HVAC NCO COM",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  17074089: {
    "BU ID": 17074089,
    "Business Units Name": "GRE HVAC NCO MFY",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  17074090: {
    "BU ID": 17074090,
    "Business Units Name": "GRE HVAC NCO RES",
    "Account Type": "HVAC",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  17074091: {
    "BU ID": 17074091,
    "Business Units Name": "GRE HVAC SRV COM",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  17074092: {
    "BU ID": 17074092,
    "Business Units Name": "GRE HVAC SRV MFY",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  17074093: {
    "BU ID": 17074093,
    "Business Units Name": "GRE HVAC SRV RES",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  17074094: {
    "BU ID": 17074094,
    "Business Units Name": "GRE OTHR AOR COM",
    "Account Type": "OTHR",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  17074095: {
    "BU ID": 17074095,
    "Business Units Name": "GRE OTHR AOR MFY",
    "Account Type": "OTHR",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  17074096: {
    "BU ID": 17074096,
    "Business Units Name": "GRE OTHR AOR RES",
    "Account Type": "OTHR",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  17074097: {
    "BU ID": 17074097,
    "Business Units Name": "GRE OTHR MNT COM",
    "Account Type": "OTHR",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  17074098: {
    "BU ID": 17074098,
    "Business Units Name": "GRE OTHR MNT MFY",
    "Account Type": "OTHR",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  17074099: {
    "BU ID": 17074099,
    "Business Units Name": "GRE OTHR MNT RES",
    "Account Type": "OTHR",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  17074100: {
    "BU ID": 17074100,
    "Business Units Name": "GRE OTHR NCO COM",
    "Account Type": "OTHR",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  17074101: {
    "BU ID": 17074101,
    "Business Units Name": "GRE OTHR NCO MFY",
    "Account Type": "OTHR",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  17074102: {
    "BU ID": 17074102,
    "Business Units Name": "GRE OTHR NCO RES",
    "Account Type": "OTHR",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  17074103: {
    "BU ID": 17074103,
    "Business Units Name": "GRE OTHR SRV COM",
    "Account Type": "OTHR",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  17074104: {
    "BU ID": 17074104,
    "Business Units Name": "GRE OTHR SRV MFY",
    "Account Type": "OTHR",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  17074105: {
    "BU ID": 17074105,
    "Business Units Name": "GRE OTHR SRV RES",
    "Account Type": "OTHR",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  17074106: {
    "BU ID": 17074106,
    "Business Units Name": "GRE PLUM AOR COM",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "COMM",
  },
  17074107: {
    "BU ID": 17074107,
    "Business Units Name": "GRE PLUM AOR MFY",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  17074108: {
    "BU ID": 17074108,
    "Business Units Name": "GRE PLUM AOR RES",
    "Account Type": "PLUM",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  17074109: {
    "BU ID": 17074109,
    "Business Units Name": "GRE PLUM MNT COM",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "COMM",
  },
  17074110: {
    "BU ID": 17074110,
    "Business Units Name": "GRE PLUM MNT MFY",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  17074111: {
    "BU ID": 17074111,
    "Business Units Name": "GRE PLUM MNT RES",
    "Account Type": "PLUM",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
  17074112: {
    "BU ID": 17074112,
    "Business Units Name": "GRE PLUM NCO COM",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "COMM",
  },
  17074113: {
    "BU ID": 17074113,
    "Business Units Name": "GRE PLUM NCO MFY",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  17074114: {
    "BU ID": 17074114,
    "Business Units Name": "GRE PLUM NCO RES",
    "Account Type": "PLUM",
    "Revenue Type": "NCO",
    "Trade Type": "RES",
  },
  17074115: {
    "BU ID": 17074115,
    "Business Units Name": "GRE PLUM SRV COM",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "COMM",
  },
  17074116: {
    "BU ID": 17074116,
    "Business Units Name": "GRE PLUM SRV MFY",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  17074117: {
    "BU ID": 17074117,
    "Business Units Name": "GRE PLUM SRV RES",
    "Account Type": "PLUM",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  35405856: {
    "BU ID": 35405856,
    "Business Units Name": "GRE ADMN GEN OFF",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  51353626: {
    "BU ID": 51353626,
    "Business Units Name": "FHC ADMN GEN OFF",
    "Account Type": "EXP",
    "Revenue Type": "EXP",
    "Trade Type": "EXP",
  },
  55786506: {
    "BU ID": 55786506,
    "Business Units Name": "51EST-Resid Service",
    "Account Type": "HVAC",
    "Revenue Type": "SER",
    "Trade Type": "RES",
  },
  55793158: {
    "BU ID": 55793158,
    "Business Units Name": "11EST-Resid AOR",
    "Account Type": "HVAC",
    "Revenue Type": "AOR",
    "Trade Type": "RES",
  },
  55794188: {
    "BU ID": 55794188,
    "Business Units Name": "81EST-Resid Maint",
    "Account Type": "HVAC",
    "Revenue Type": "MNT",
    "Trade Type": "RES",
  },
};

module.exports = kpi_data;
