const business_unit_data = {
  "332_01": {
    "BU ID": "332_01",
    "Invoice Business Unit": "Main",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "Expert Heating & Cooling Co LLC",
  },
  "332_03": {
    "BU ID": "332_03",
    "Invoice Business Unit": "Main",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "898_02": {
    "BU ID": "898_02",
    "Invoice Business Unit": "GRE HVAC AOR RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "899_02": {
    "BU ID": "899_02",
    "Invoice Business Unit": "GRE HVAC MNT COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "900_02": {
    "BU ID": "900_02",
    "Invoice Business Unit": "Test Res HVAC Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "901_02": {
    "BU ID": "901_02",
    "Invoice Business Unit": "Plumbing - Install",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "926_02": {
    "BU ID": "926_02",
    "Invoice Business Unit": "Plumbing - Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "927_02": {
    "BU ID": "927_02",
    "Invoice Business Unit": "Plumbing - Maintenance",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "928_02": {
    "BU ID": "928_02",
    "Invoice Business Unit": "Plumbing - Sales",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "929_02": {
    "BU ID": "929_02",
    "Invoice Business Unit": "HVAC - Install",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "3330_03": {
    "BU ID": "3330_03",
    "Invoice Business Unit": "Family HVAC - Install",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "3331_03": {
    "BU ID": "3331_03",
    "Invoice Business Unit": "HVAC - Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "3332_03": {
    "BU ID": "3332_03",
    "Invoice Business Unit": "HVAC - Maintenance",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "3333_03": {
    "BU ID": "3333_03",
    "Invoice Business Unit": "HVAC - Sales",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "3346_03": {
    "BU ID": "3346_03",
    "Invoice Business Unit": "Plumbing - Install",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "3347_03": {
    "BU ID": "3347_03",
    "Invoice Business Unit": "Plumbing - Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "3348_03": {
    "BU ID": "3348_03",
    "Invoice Business Unit": "Plumbing - Maintenance",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "3349_03": {
    "BU ID": "3349_03",
    "Invoice Business Unit": "Plumbing - Sales",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "3458_03": {
    "BU ID": "3458_03",
    "Invoice Business Unit": "HVAC - Sprays Plumbing and Heating",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "3459_03": {
    "BU ID": "3459_03",
    "Invoice Business Unit": "Plumbing - Sprays Plumbing and Heating",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  "3864_02": {
    "BU ID": "3864_02",
    "Invoice Business Unit": "HVAC - Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "3865_02": {
    "BU ID": "3865_02",
    "Invoice Business Unit": "HVAC - Maintenance",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "3866_02": {
    "BU ID": "3866_02",
    "Invoice Business Unit": "HVAC - Sales",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "3867_02": {
    "BU ID": "3867_02",
    "Invoice Business Unit": "Imported Default Businessunit",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "108709_01": {
    "BU ID": "108709_01",
    "Invoice Business Unit": "Imported Default Businessunit",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  "112805_02": {
    "BU ID": "112805_02",
    "Invoice Business Unit": "GRE HVAC AOR COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "166181_03": {
    "BU ID": "166181_03",
    "Invoice Business Unit": "Imported Default Businessunit",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Imported Default Business Unit",
  },
  "1000004_01": {
    "BU ID": "1000004_01",
    "Invoice Business Unit": "Imported Businessunit",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  "1034876_01": {
    "BU ID": "1034876_01",
    "Invoice Business Unit": "10EXP-Resid AOR",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "EXP",
    Name: "Expert Residential AOR",
  },
  "1034877_01": {
    "BU ID": "1034877_01",
    "Invoice Business Unit": "20EXP-Resid NC",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "EXP",
    Name: "Expert Residential New Const",
  },
  "1034878_01": {
    "BU ID": "1034878_01",
    "Invoice Business Unit": "30EXP-Comm AOR",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "EXP",
    Name: "Expert Commercial AOR",
  },
  "1034879_01": {
    "BU ID": "1034879_01",
    "Invoice Business Unit": "40EXP-Comm NC",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "EXP",
    Name: "Expert Commercial New Constr",
  },
  "1034880_01": {
    "BU ID": "1034880_01",
    "Invoice Business Unit": "50EXP-Resid Service",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Residential Service",
  },
  "1034881_01": {
    "BU ID": "1034881_01",
    "Invoice Business Unit": "60EXP-Comm Service",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Commercial Service",
  },
  "1034882_01": {
    "BU ID": "1034882_01",
    "Invoice Business Unit": "70EXP-OTC",
    Trade: "HVAC",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "Expert Over the Counter",
  },
  "1034883_01": {
    "BU ID": "1034883_01",
    "Invoice Business Unit": "80EXP-Resid Maint",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Residential Maintenance",
  },
  "1034884_01": {
    "BU ID": "1034884_01",
    "Invoice Business Unit": "90EXP-Comm Maint",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Commercial Maintenance",
  },
  "1034885_01": {
    "BU ID": "1034885_01",
    "Invoice Business Unit": "CTM-Commercial Time & Material",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  "1034886_01": {
    "BU ID": "1034886_01",
    "Invoice Business Unit": "RES SERVIC-W/O Billings - Res Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  "1034887_01": {
    "BU ID": "1034887_01",
    "Invoice Business Unit": "SVC.CONT-Service Contracts",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  "1034888_01": {
    "BU ID": "1034888_01",
    "Invoice Business Unit": "UNAPP-Unapplied Receipts",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  "1951850_01": {
    "BU ID": "1951850_01",
    "Invoice Business Unit": "EXP00-HEAD OFFICE",
    Trade: "HVAC",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "EXP00 HEAD OFFICE",
  },
  "1951978_01": {
    "BU ID": "1951978_01",
    "Invoice Business Unit": "EXP01-ADMIN/OFFICE",
    Trade: "HVAC",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "EXP01-ADMINISTRATION/OFFICE",
  },
  "1952106_01": {
    "BU ID": "1952106_01",
    "Invoice Business Unit": "EXP03-SHEET METAL SHOP",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "EXP03-SHEET METAL SHOP",
  },
  "1952234_01": {
    "BU ID": "1952234_01",
    "Invoice Business Unit": "EXP04-FACILITY/BLDG",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "EXP04-FACILITY/BLDG",
  },
  "1952362_01": {
    "BU ID": "1952362_01",
    "Invoice Business Unit": "EXP02-WAREHOUSE",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "EXP02-WAREHOUSE",
  },
  "4078369_01": {
    "BU ID": "4078369_01",
    "Invoice Business Unit": "10-Residential AOR",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "EXP",
    Name: "",
  },
  "4078370_01": {
    "BU ID": "4078370_01",
    "Invoice Business Unit": "20-Residential New Construction",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "EXP",
    Name: "",
  },
  "4078371_01": {
    "BU ID": "4078371_01",
    "Invoice Business Unit": "30-Commercial AOR",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "EXP",
    Name: "",
  },
  "4078372_01": {
    "BU ID": "4078372_01",
    "Invoice Business Unit": "40-Commercial New Construction",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "EXP",
    Name: "",
  },
  "4078373_01": {
    "BU ID": "4078373_01",
    "Invoice Business Unit": "50-Residential Service",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "",
  },
  "4078374_01": {
    "BU ID": "4078374_01",
    "Invoice Business Unit": "60-Commercial Service",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "",
  },
  "4078375_01": {
    "BU ID": "4078375_01",
    "Invoice Business Unit": "70-Over the Counter Retail",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  "4078376_01": {
    "BU ID": "4078376_01",
    "Invoice Business Unit": "80-Residential Maintenance",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "",
  },
  "4078377_01": {
    "BU ID": "4078377_01",
    "Invoice Business Unit": "90-Commercial Maintenance",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "",
  },
  "9722674_02": {
    "BU ID": "9722674_02",
    "Invoice Business Unit": "GRE HVAC AOR MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "11152547_03": {
    "BU ID": "11152547_03",
    "Invoice Business Unit": "FAM HVAC AOR COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "11156642_03": {
    "BU ID": "11156642_03",
    "Invoice Business Unit": "HAN HVAC AOR COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "11156773_03": {
    "BU ID": "11156773_03",
    "Invoice Business Unit": "SPR HVAC AOR COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "11157153_03": {
    "BU ID": "11157153_03",
    "Invoice Business Unit": "KNL HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "13107263_03": {
    "BU ID": "13107263_03",
    "Invoice Business Unit": "FAM HVAC AOR MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  "13107264_03": {
    "BU ID": "13107264_03",
    "Invoice Business Unit": "FAM HVAC AOR RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107265_03": {
    "BU ID": "13107265_03",
    "Invoice Business Unit": "FAM HVAC MNT COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107266_03": {
    "BU ID": "13107266_03",
    "Invoice Business Unit": "FAM HVAC MNT MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  "13107267_03": {
    "BU ID": "13107267_03",
    "Invoice Business Unit": "FAM HVAC MNT RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107268_03": {
    "BU ID": "13107268_03",
    "Invoice Business Unit": "FAM HVAC SRV COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107269_03": {
    "BU ID": "13107269_03",
    "Invoice Business Unit": "FAM HVAC SRV MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  "13107270_03": {
    "BU ID": "13107270_03",
    "Invoice Business Unit": "FAM HVAC SRV RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107271_03": {
    "BU ID": "13107271_03",
    "Invoice Business Unit": "FAM PLUM AOR COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107272_03": {
    "BU ID": "13107272_03",
    "Invoice Business Unit": "FAM PLUM AOR MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  "13107273_03": {
    "BU ID": "13107273_03",
    "Invoice Business Unit": "FAM PLUM AOR RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107274_03": {
    "BU ID": "13107274_03",
    "Invoice Business Unit": "FAM PLUM MNT COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107275_03": {
    "BU ID": "13107275_03",
    "Invoice Business Unit": "FAM PLUM MNT MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  "13107276_03": {
    "BU ID": "13107276_03",
    "Invoice Business Unit": "FAM PLUM MNT RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107277_03": {
    "BU ID": "13107277_03",
    "Invoice Business Unit": "FAM PLUM SRV COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107278_03": {
    "BU ID": "13107278_03",
    "Invoice Business Unit": "FAM PLUM SRV MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  "13107279_03": {
    "BU ID": "13107279_03",
    "Invoice Business Unit": "FAM PLUM SRV RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "13107280_03": {
    "BU ID": "13107280_03",
    "Invoice Business Unit": "HAN HVAC AOR MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107281_03": {
    "BU ID": "13107281_03",
    "Invoice Business Unit": "HAN HVAC AOR RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107282_03": {
    "BU ID": "13107282_03",
    "Invoice Business Unit": "HAN HVAC MNT COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107283_03": {
    "BU ID": "13107283_03",
    "Invoice Business Unit": "HAN HVAC MNT MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107284_03": {
    "BU ID": "13107284_03",
    "Invoice Business Unit": "HAN HVAC MNT RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107285_03": {
    "BU ID": "13107285_03",
    "Invoice Business Unit": "HAN HVAC SRV COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107286_03": {
    "BU ID": "13107286_03",
    "Invoice Business Unit": "HAN HVAC SRV MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107287_03": {
    "BU ID": "13107287_03",
    "Invoice Business Unit": "HAN HVAC SRV RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107288_03": {
    "BU ID": "13107288_03",
    "Invoice Business Unit": "HAN PLUM AOR COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107289_03": {
    "BU ID": "13107289_03",
    "Invoice Business Unit": "HAN PLUM AOR MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107290_03": {
    "BU ID": "13107290_03",
    "Invoice Business Unit": "HAN PLUM AOR RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107291_03": {
    "BU ID": "13107291_03",
    "Invoice Business Unit": "HAN PLUM MNT COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107292_03": {
    "BU ID": "13107292_03",
    "Invoice Business Unit": "HAN PLUM MNT MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107293_03": {
    "BU ID": "13107293_03",
    "Invoice Business Unit": "HAN PLUM MNT RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107294_03": {
    "BU ID": "13107294_03",
    "Invoice Business Unit": "HAN PLUM SRV COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107295_03": {
    "BU ID": "13107295_03",
    "Invoice Business Unit": "HAN PLUM SRV MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107296_03": {
    "BU ID": "13107296_03",
    "Invoice Business Unit": "HAN PLUM SRV RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "13107297_03": {
    "BU ID": "13107297_03",
    "Invoice Business Unit": "KNL HVAC NCO MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "13107298_03": {
    "BU ID": "13107298_03",
    "Invoice Business Unit": "KNL HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "13107299_03": {
    "BU ID": "13107299_03",
    "Invoice Business Unit": "KNL OTHR NCO COM",
    Trade: "OTHER",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "13107300_03": {
    "BU ID": "13107300_03",
    "Invoice Business Unit": "KNL OTHR NCO MFY",
    Trade: "OTHER",
    Segment: "MULTI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "13107301_03": {
    "BU ID": "13107301_03",
    "Invoice Business Unit": "KNL OTHR NCO RES",
    Trade: "OTHER",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "13107302_03": {
    "BU ID": "13107302_03",
    "Invoice Business Unit": "KNL PLUM NCO COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "13107303_03": {
    "BU ID": "13107303_03",
    "Invoice Business Unit": "KNL PLUM NCO MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "13107304_03": {
    "BU ID": "13107304_03",
    "Invoice Business Unit": "KNL PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "13107305_03": {
    "BU ID": "13107305_03",
    "Invoice Business Unit": "SPR HVAC AOR MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  "13107306_03": {
    "BU ID": "13107306_03",
    "Invoice Business Unit": "SPR HVAC AOR RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "13107307_03": {
    "BU ID": "13107307_03",
    "Invoice Business Unit": "SPR HVAC MNT COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "13107308_03": {
    "BU ID": "13107308_03",
    "Invoice Business Unit": "SPR HVAC MNT MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  "13107309_03": {
    "BU ID": "13107309_03",
    "Invoice Business Unit": "SPR HVAC MNT RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "13107310_03": {
    "BU ID": "13107310_03",
    "Invoice Business Unit": "SPR HVAC SRV COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "13107311_03": {
    "BU ID": "13107311_03",
    "Invoice Business Unit": "SPR HVAC SRV MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  "13107312_03": {
    "BU ID": "13107312_03",
    "Invoice Business Unit": "SPR HVAC SRV RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "13107313_03": {
    "BU ID": "13107313_03",
    "Invoice Business Unit": "SPR PLUM AOR COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "13107314_03": {
    "BU ID": "13107314_03",
    "Invoice Business Unit": "SPR PLUM AOR MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  "13107315_03": {
    "BU ID": "13107315_03",
    "Invoice Business Unit": "SPR PLUM AOR RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "13107316_03": {
    "BU ID": "13107316_03",
    "Invoice Business Unit": "SPR PLUM MNT COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "13107317_03": {
    "BU ID": "13107317_03",
    "Invoice Business Unit": "SPR PLUM MNT MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  "13107318_03": {
    "BU ID": "13107318_03",
    "Invoice Business Unit": "SPR PLUM MNT RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "13107319_03": {
    "BU ID": "13107319_03",
    "Invoice Business Unit": "SPR PLUM SRV COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "13107320_03": {
    "BU ID": "13107320_03",
    "Invoice Business Unit": "SPR PLUM SRV MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  "13107321_03": {
    "BU ID": "13107321_03",
    "Invoice Business Unit": "SPR PLUM SRV RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "16118462_03": {
    "BU ID": "16118462_03",
    "Invoice Business Unit": "FAM ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "16118463_03": {
    "BU ID": "16118463_03",
    "Invoice Business Unit": "FAM HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "16118464_03": {
    "BU ID": "16118464_03",
    "Invoice Business Unit": "FAM HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "16118465_03": {
    "BU ID": "16118465_03",
    "Invoice Business Unit": "FAM PLUM NCO COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "16118466_03": {
    "BU ID": "16118466_03",
    "Invoice Business Unit": "FAM PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  "16118467_03": {
    "BU ID": "16118467_03",
    "Invoice Business Unit": "HAN ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "16118468_03": {
    "BU ID": "16118468_03",
    "Invoice Business Unit": "HAN HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "16118469_03": {
    "BU ID": "16118469_03",
    "Invoice Business Unit": "HAN HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "16118470_03": {
    "BU ID": "16118470_03",
    "Invoice Business Unit": "HAN PLUM NCO COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "16118471_03": {
    "BU ID": "16118471_03",
    "Invoice Business Unit": "HAN PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  "16118472_03": {
    "BU ID": "16118472_03",
    "Invoice Business Unit": "KNL ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118473_03": {
    "BU ID": "16118473_03",
    "Invoice Business Unit": "KNL HVAC AOR COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118474_03": {
    "BU ID": "16118474_03",
    "Invoice Business Unit": "KNL HVAC AOR RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118475_03": {
    "BU ID": "16118475_03",
    "Invoice Business Unit": "KNL HVAC MNT COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118476_03": {
    "BU ID": "16118476_03",
    "Invoice Business Unit": "KNL HVAC MNT RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118477_03": {
    "BU ID": "16118477_03",
    "Invoice Business Unit": "KNL HVAC SRV COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118478_03": {
    "BU ID": "16118478_03",
    "Invoice Business Unit": "KNL HVAC SRV RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118479_03": {
    "BU ID": "16118479_03",
    "Invoice Business Unit": "KNL PLUM AOR COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118480_03": {
    "BU ID": "16118480_03",
    "Invoice Business Unit": "KNL PLUM AOR RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118481_03": {
    "BU ID": "16118481_03",
    "Invoice Business Unit": "KNL PLUM MNT COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118482_03": {
    "BU ID": "16118482_03",
    "Invoice Business Unit": "KNL PLUM MNT RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118483_03": {
    "BU ID": "16118483_03",
    "Invoice Business Unit": "KNL PLUM SRV COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118484_03": {
    "BU ID": "16118484_03",
    "Invoice Business Unit": "KNL PLUM SRV RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  "16118485_03": {
    "BU ID": "16118485_03",
    "Invoice Business Unit": "SPR ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family North Plumbing & Heating",
  },
  "16118486_03": {
    "BU ID": "16118486_03",
    "Invoice Business Unit": "SPR HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "16118487_03": {
    "BU ID": "16118487_03",
    "Invoice Business Unit": "SPR HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "16118488_03": {
    "BU ID": "16118488_03",
    "Invoice Business Unit": "SPR PLUM NCO COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "16118489_03": {
    "BU ID": "16118489_03",
    "Invoice Business Unit": "SPR PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  "17074086_02": {
    "BU ID": "17074086_02",
    "Invoice Business Unit": "GRE HVAC MNT MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074087_02": {
    "BU ID": "17074087_02",
    "Invoice Business Unit": "GRE HVAC MNT RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074088_02": {
    "BU ID": "17074088_02",
    "Invoice Business Unit": "GRE HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074089_02": {
    "BU ID": "17074089_02",
    "Invoice Business Unit": "GRE HVAC NCO MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074090_02": {
    "BU ID": "17074090_02",
    "Invoice Business Unit": "GRE HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074091_02": {
    "BU ID": "17074091_02",
    "Invoice Business Unit": "GRE HVAC SRV COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074092_02": {
    "BU ID": "17074092_02",
    "Invoice Business Unit": "GRE HVAC SRV MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074093_02": {
    "BU ID": "17074093_02",
    "Invoice Business Unit": "GRE HVAC SRV RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074094_02": {
    "BU ID": "17074094_02",
    "Invoice Business Unit": "GRE OTHR AOR COM",
    Trade: "OTHER",
    Segment: "COM",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074095_02": {
    "BU ID": "17074095_02",
    "Invoice Business Unit": "GRE OTHR AOR MFY",
    Trade: "OTHER",
    Segment: "MULTI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074096_02": {
    "BU ID": "17074096_02",
    "Invoice Business Unit": "GRE OTHR AOR RES",
    Trade: "OTHER",
    Segment: "RESI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074097_02": {
    "BU ID": "17074097_02",
    "Invoice Business Unit": "GRE OTHR MNT COM",
    Trade: "OTHER",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074098_02": {
    "BU ID": "17074098_02",
    "Invoice Business Unit": "GRE OTHR MNT MFY",
    Trade: "OTHER",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074099_02": {
    "BU ID": "17074099_02",
    "Invoice Business Unit": "GRE OTHR MNT RES",
    Trade: "OTHER",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074100_02": {
    "BU ID": "17074100_02",
    "Invoice Business Unit": "GRE OTHR NCO COM",
    Trade: "OTHER",
    Segment: "COM",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074101_02": {
    "BU ID": "17074101_02",
    "Invoice Business Unit": "GRE OTHR NCO MFY",
    Trade: "OTHER",
    Segment: "MULTI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074102_02": {
    "BU ID": "17074102_02",
    "Invoice Business Unit": "GRE OTHR NCO RES",
    Trade: "OTHER",
    Segment: "RESI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074103_02": {
    "BU ID": "17074103_02",
    "Invoice Business Unit": "GRE OTHR SRV COM",
    Trade: "OTHER",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074104_02": {
    "BU ID": "17074104_02",
    "Invoice Business Unit": "GRE OTHR SRV MFY",
    Trade: "OTHER",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074105_02": {
    "BU ID": "17074105_02",
    "Invoice Business Unit": "GRE OTHR SRV RES",
    Trade: "OTHER",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074106_02": {
    "BU ID": "17074106_02",
    "Invoice Business Unit": "GRE PLUM AOR COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074107_02": {
    "BU ID": "17074107_02",
    "Invoice Business Unit": "GRE PLUM AOR MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074108_02": {
    "BU ID": "17074108_02",
    "Invoice Business Unit": "GRE PLUM AOR RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074109_02": {
    "BU ID": "17074109_02",
    "Invoice Business Unit": "GRE PLUM MNT COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074110_02": {
    "BU ID": "17074110_02",
    "Invoice Business Unit": "GRE PLUM MNT MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074111_02": {
    "BU ID": "17074111_02",
    "Invoice Business Unit": "GRE PLUM MNT RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074112_02": {
    "BU ID": "17074112_02",
    "Invoice Business Unit": "GRE PLUM NCO COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074113_02": {
    "BU ID": "17074113_02",
    "Invoice Business Unit": "GRE PLUM NCO MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074114_02": {
    "BU ID": "17074114_02",
    "Invoice Business Unit": "GRE PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074115_02": {
    "BU ID": "17074115_02",
    "Invoice Business Unit": "GRE PLUM SRV COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074116_02": {
    "BU ID": "17074116_02",
    "Invoice Business Unit": "GRE PLUM SRV MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "17074117_02": {
    "BU ID": "17074117_02",
    "Invoice Business Unit": "GRE PLUM SRV RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "30818702_02": {
    "BU ID": "30818702_02",
    "Invoice Business Unit": "GKB Test BU",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "35405856_02": {
    "BU ID": "35405856_02",
    "Invoice Business Unit": "GRE ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  "51353626_03": {
    "BU ID": "51353626_03",
    "Invoice Business Unit": "FHC ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Headquarters",
  },
  "55786506_01": {
    "BU ID": "55786506_01",
    "Invoice Business Unit": "51EST-Resid Service",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Residential Service",
  },
  "55793158_01": {
    "BU ID": "55793158_01",
    "Invoice Business Unit": "11EST-Resid AOR",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "EXP",
    Name: "Expert Residential AOR",
  },
  "55793418_01": {
    "BU ID": "55793418_01",
    "Invoice Business Unit": "61EST-Comm Service",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "EAST COMMERCIAL SERVICE",
  },
  "55794188_01": {
    "BU ID": "55794188_01",
    "Invoice Business Unit": "81EST-Resid Maint",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Residential Maintenance",
  },
  "55794694_01": {
    "BU ID": "55794694_01",
    "Invoice Business Unit": "21EST-Resid NC",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "EXP",
    Name: "EST RESIDENTIAL NEW CONST",
  },
  "55796230_01": {
    "BU ID": "55796230_01",
    "Invoice Business Unit": "91EST-Comm Maint",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "EST COMMERCIAL MAINT",
  },
  "63418507_01": {
    "BU ID": "63418507_01",
    "Invoice Business Unit": "31EST-Comm AOR",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "EXP",
    Name: "EAST COMMERCIAL AOR",
  },
  "79899215_01": {
    "BU ID": "79899215_01",
    "Invoice Business Unit": "12AA-Resid AOR",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "EXP",
    Name: "Jetstream Residential AOR",
  },
};

module.exports = business_unit_data;
