const business_unit_data = {
  11152547: {
    "BU ID": "11152547",
    "Invoice Business Unit": "FAM HVAC AOR COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  11156642: {
    "BU ID": "11156642",
    "Invoice Business Unit": "HAN HVAC AOR COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  11156773: {
    "BU ID": "11156773",
    "Invoice Business Unit": "SPR HVAC AOR COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  11157153: {
    "BU ID": "11157153",
    "Invoice Business Unit": "KNL HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  13107264: {
    "BU ID": "13107264",
    "Invoice Business Unit": "FAM HVAC AOR RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107265: {
    "BU ID": "13107265",
    "Invoice Business Unit": "FAM HVAC MNT COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107267: {
    "BU ID": "13107267",
    "Invoice Business Unit": "FAM HVAC MNT RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107268: {
    "BU ID": "13107268",
    "Invoice Business Unit": "FAM HVAC SRV COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107270: {
    "BU ID": "13107270",
    "Invoice Business Unit": "FAM HVAC SRV RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107271: {
    "BU ID": "13107271",
    "Invoice Business Unit": "FAM PLUM AOR COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107273: {
    "BU ID": "13107273",
    "Invoice Business Unit": "FAM PLUM AOR RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107274: {
    "BU ID": "13107274",
    "Invoice Business Unit": "FAM PLUM MNT COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107276: {
    "BU ID": "13107276",
    "Invoice Business Unit": "FAM PLUM MNT RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107277: {
    "BU ID": "13107277",
    "Invoice Business Unit": "FAM PLUM SRV COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107279: {
    "BU ID": "13107279",
    "Invoice Business Unit": "FAM PLUM SRV RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  13107281: {
    "BU ID": "13107281",
    "Invoice Business Unit": "HAN HVAC AOR RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  13107282: {
    "BU ID": "13107282",
    "Invoice Business Unit": "HAN HVAC MNT COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  13107284: {
    "BU ID": "13107284",
    "Invoice Business Unit": "HAN HVAC MNT RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  13107285: {
    "BU ID": "13107285",
    "Invoice Business Unit": "HAN HVAC SRV COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  13107287: {
    "BU ID": "13107287",
    "Invoice Business Unit": "HAN HVAC SRV RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  13107288: {
    "BU ID": "13107288",
    "Invoice Business Unit": "HAN PLUM AOR COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  13107290: {
    "BU ID": "13107290",
    "Invoice Business Unit": "HAN PLUM AOR RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  13107296: {
    "BU ID": "13107296",
    "Invoice Business Unit": "HAN PLUM SRV RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  13107298: {
    "BU ID": "13107298",
    "Invoice Business Unit": "KNL HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  13107302: {
    "BU ID": "13107302",
    "Invoice Business Unit": "KNL PLUM NCO COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  13107304: {
    "BU ID": "13107304",
    "Invoice Business Unit": "KNL PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  13107306: {
    "BU ID": "13107306",
    "Invoice Business Unit": "SPR HVAC AOR RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  13107307: {
    "BU ID": "13107307",
    "Invoice Business Unit": "SPR HVAC MNT COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  13107309: {
    "BU ID": "13107309",
    "Invoice Business Unit": "SPR HVAC MNT RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  13107310: {
    "BU ID": "13107310",
    "Invoice Business Unit": "SPR HVAC SRV COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  13107312: {
    "BU ID": "13107312",
    "Invoice Business Unit": "SPR HVAC SRV RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  13107315: {
    "BU ID": "13107315",
    "Invoice Business Unit": "SPR PLUM AOR RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  13107319: {
    "BU ID": "13107319",
    "Invoice Business Unit": "SPR PLUM SRV COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  13107321: {
    "BU ID": "13107321",
    "Invoice Business Unit": "SPR PLUM SRV RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  16118462: {
    "BU ID": "16118462",
    "Invoice Business Unit": "FAM ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  16118464: {
    "BU ID": "16118464",
    "Invoice Business Unit": "FAM HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  16118467: {
    "BU ID": "16118467",
    "Invoice Business Unit": "HAN ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  16118469: {
    "BU ID": "16118469",
    "Invoice Business Unit": "HAN HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Hank's Heating & Cooling",
  },
  16118472: {
    "BU ID": "16118472",
    "Invoice Business Unit": "KNL ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118473: {
    "BU ID": "16118473",
    "Invoice Business Unit": "KNL HVAC AOR COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118474: {
    "BU ID": "16118474",
    "Invoice Business Unit": "KNL HVAC AOR RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118475: {
    "BU ID": "16118475",
    "Invoice Business Unit": "KNL HVAC MNT COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118476: {
    "BU ID": "16118476",
    "Invoice Business Unit": "KNL HVAC MNT RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118477: {
    "BU ID": "16118477",
    "Invoice Business Unit": "KNL HVAC SRV COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118478: {
    "BU ID": "16118478",
    "Invoice Business Unit": "KNL HVAC SRV RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118479: {
    "BU ID": "16118479",
    "Invoice Business Unit": "KNL PLUM AOR COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118480: {
    "BU ID": "16118480",
    "Invoice Business Unit": "KNL PLUM AOR RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "AOR",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118482: {
    "BU ID": "16118482",
    "Invoice Business Unit": "KNL PLUM MNT RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118483: {
    "BU ID": "16118483",
    "Invoice Business Unit": "KNL PLUM SRV COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118484: {
    "BU ID": "16118484",
    "Invoice Business Unit": "KNL PLUM SRV RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118485: {
    "BU ID": "16118485",
    "Invoice Business Unit": "SPR ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family North Plumbing & Heating",
  },
  16118486: {
    "BU ID": "16118486",
    "Invoice Business Unit": "SPR HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  16118487: {
    "BU ID": "16118487",
    "Invoice Business Unit": "SPR HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  16118489: {
    "BU ID": "16118489",
    "Invoice Business Unit": "SPR PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  332: {
    "BU ID": "332",
    "Invoice Business Unit": "Main",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3330: {
    "BU ID": "3330",
    "Invoice Business Unit": "Family HVAC - Install",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3331: {
    "BU ID": "3331",
    "Invoice Business Unit": "HVAC - Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3332: {
    "BU ID": "3332",
    "Invoice Business Unit": "HVAC - Maintenance",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3333: {
    "BU ID": "3333",
    "Invoice Business Unit": "HVAC - Sales",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3346: {
    "BU ID": "3346",
    "Invoice Business Unit": "Plumbing - Install",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  16118485: {
    "BU ID": "16118485",
    "Invoice Business Unit": "SPR ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family North Plumbing & Heating",
  },
  16118486: {
    "BU ID": "16118486",
    "Invoice Business Unit": "SPR HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  16118487: {
    "BU ID": "16118487",
    "Invoice Business Unit": "SPR HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  16118489: {
    "BU ID": "16118489",
    "Invoice Business Unit": "SPR PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  332: {
    "BU ID": "332",
    "Invoice Business Unit": "Main",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3330: {
    "BU ID": "3330",
    "Invoice Business Unit": "Family HVAC - Install",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3331: {
    "BU ID": "3331",
    "Invoice Business Unit": "HVAC - Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3332: {
    "BU ID": "3332",
    "Invoice Business Unit": "HVAC - Maintenance",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3333: {
    "BU ID": "3333",
    "Invoice Business Unit": "HVAC - Sales",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3346: {
    "BU ID": "3346",
    "Invoice Business Unit": "Plumbing - Install",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3347: {
    "BU ID": "3347",
    "Invoice Business Unit": "Plumbing - Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3348: {
    "BU ID": "3348",
    "Invoice Business Unit": "Plumbing - Maintenance",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3349: {
    "BU ID": "3349",
    "Invoice Business Unit": "Plumbing - Sales",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3458: {
    "BU ID": "3458",
    "Invoice Business Unit": "HVAC - Sprays Plumbing and Heating",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  3459: {
    "BU ID": "3459",
    "Invoice Business Unit": "Plumbing - Sprays Plumbing and Heating",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Heating & Cooling Co Inc",
  },
  166181: {
    "BU ID": "166181",
    "Invoice Business Unit": "Imported Default Businessunit",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Imported Default Business Unit",
  },
  13107263: {
    "BU ID": "13107263",
    "Invoice Business Unit": "FAM HVAC AOR MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  13107266: {
    "BU ID": "13107266",
    "Invoice Business Unit": "FAM HVAC MNT MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  13107269: {
    "BU ID": "13107269",
    "Invoice Business Unit": "FAM HVAC SRV MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  13107272: {
    "BU ID": "13107272",
    "Invoice Business Unit": "FAM PLUM AOR MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  13107275: {
    "BU ID": "13107275",
    "Invoice Business Unit": "FAM PLUM MNT MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  13107278: {
    "BU ID": "13107278",
    "Invoice Business Unit": "FAM PLUM SRV MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating Co Inc",
  },
  13107280: {
    "BU ID": "13107280",
    "Invoice Business Unit": "HAN HVAC AOR MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  13107283: {
    "BU ID": "13107283",
    "Invoice Business Unit": "HAN HVAC MNT MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  13107286: {
    "BU ID": "13107286",
    "Invoice Business Unit": "HAN HVAC SRV MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  13107289: {
    "BU ID": "13107289",
    "Invoice Business Unit": "HAN PLUM AOR MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  13107291: {
    "BU ID": "13107291",
    "Invoice Business Unit": "HAN PLUM MNT COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  13107292: {
    "BU ID": "13107292",
    "Invoice Business Unit": "HAN PLUM MNT MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  13107293: {
    "BU ID": "13107293",
    "Invoice Business Unit": "HAN PLUM MNT RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  13107294: {
    "BU ID": "13107294",
    "Invoice Business Unit": "HAN PLUM SRV COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  13107295: {
    "BU ID": "13107295",
    "Invoice Business Unit": "HAN PLUM SRV MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  13107297: {
    "BU ID": "13107297",
    "Invoice Business Unit": "KNL HVAC NCO MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  13107299: {
    "BU ID": "13107299",
    "Invoice Business Unit": "KNL OTHR NCO COM",
    Trade: "OTHR",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  13107300: {
    "BU ID": "13107300",
    "Invoice Business Unit": "KNL OTHR NCO MFY",
    Trade: "OTHR",
    Segment: "MULTI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  13107301: {
    "BU ID": "13107301",
    "Invoice Business Unit": "KNL OTHR NCO RES",
    Trade: "OTHR",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  13107303: {
    "BU ID": "13107303",
    "Invoice Business Unit": "KNL PLUM NCO MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "NCO",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  13107305: {
    "BU ID": "13107305",
    "Invoice Business Unit": "SPR HVAC AOR MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  13107308: {
    "BU ID": "13107308",
    "Invoice Business Unit": "SPR HVAC MNT MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  13107311: {
    "BU ID": "13107311",
    "Invoice Business Unit": "SPR HVAC SRV MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  13107313: {
    "BU ID": "13107313",
    "Invoice Business Unit": "SPR PLUM AOR COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "AOR",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  13107314: {
    "BU ID": "13107314",
    "Invoice Business Unit": "SPR PLUM AOR MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "AOR",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  13107316: {
    "BU ID": "13107316",
    "Invoice Business Unit": "SPR PLUM MNT COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  13107317: {
    "BU ID": "13107317",
    "Invoice Business Unit": "SPR PLUM MNT MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  13107318: {
    "BU ID": "13107318",
    "Invoice Business Unit": "SPR PLUM MNT RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  13107320: {
    "BU ID": "13107320",
    "Invoice Business Unit": "SPR PLUM SRV MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "NMI",
    Name: "Family Plumbing & Heating North",
  },
  16118463: {
    "BU ID": "16118463",
    "Invoice Business Unit": "FAM HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  16118465: {
    "BU ID": "16118465",
    "Invoice Business Unit": "FAM PLUM NCO COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  16118466: {
    "BU ID": "16118466",
    "Invoice Business Unit": "FAM PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Family Plumbing & Heating",
  },
  16118468: {
    "BU ID": "16118468",
    "Invoice Business Unit": "HAN HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  16118470: {
    "BU ID": "16118470",
    "Invoice Business Unit": "HAN PLUM NCO COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  16118471: {
    "BU ID": "16118471",
    "Invoice Business Unit": "HAN PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "NMI",
    Name: "Hank''s Heating & Cooling",
  },
  16118481: {
    "BU ID": "16118481",
    "Invoice Business Unit": "KNL PLUM MNT COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "NMI",
    Name: "K&L Plumbing and Heating",
  },
  16118488: {
    "BU ID": "16118488",
    "Invoice Business Unit": "SPR PLUM NCO COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "NCO",
    Business: "NMI",
    Name: "Family North Plumbing and Heating",
  },
  51353626: {
    "BU ID": "51353626",
    "Invoice Business Unit": "FHC ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "NMI",
    Name: "Family Headquarters",
  },
  898: {
    "BU ID": "898",
    "Invoice Business Unit": "GRE HVAC AOR RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  899: {
    "BU ID": "899",
    "Invoice Business Unit": "GRE HVAC MNT COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  112805: {
    "BU ID": "112805",
    "Invoice Business Unit": "GRE HVAC AOR COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  9722674: {
    "BU ID": "9722674",
    "Invoice Business Unit": "GRE HVAC AOR MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074086: {
    "BU ID": "17074086",
    "Invoice Business Unit": "GRE HVAC MNT MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074087: {
    "BU ID": "17074087",
    "Invoice Business Unit": "GRE HVAC MNT RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074088: {
    "BU ID": "17074088",
    "Invoice Business Unit": "GRE HVAC NCO COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074089: {
    "BU ID": "17074089",
    "Invoice Business Unit": "GRE HVAC NCO MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074090: {
    "BU ID": "17074090",
    "Invoice Business Unit": "GRE HVAC NCO RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074091: {
    "BU ID": "17074091",
    "Invoice Business Unit": "GRE HVAC SRV COM",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074092: {
    "BU ID": "17074092",
    "Invoice Business Unit": "GRE HVAC SRV MFY",
    Trade: "HVAC",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074093: {
    "BU ID": "17074093",
    "Invoice Business Unit": "GRE HVAC SRV RES",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074094: {
    "BU ID": "17074094",
    "Invoice Business Unit": "GRE OTHR AOR COM",
    Trade: "OTHER",
    Segment: "COM",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074095: {
    "BU ID": "17074095",
    "Invoice Business Unit": "GRE OTHR AOR MFY",
    Trade: "OTHER",
    Segment: "MULTI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074096: {
    "BU ID": "17074096",
    "Invoice Business Unit": "GRE OTHR AOR RES",
    Trade: "OTHER",
    Segment: "RESI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074098: {
    "BU ID": "17074098",
    "Invoice Business Unit": "GRE OTHR MNT MFY",
    Trade: "OTHER",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074101: {
    "BU ID": "17074101",
    "Invoice Business Unit": "GRE OTHR NCO MFY",
    Trade: "OTHER",
    Segment: "MULTI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074104: {
    "BU ID": "17074104",
    "Invoice Business Unit": "GRE OTHR SRV MFY",
    Trade: "OTHER",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074105: {
    "BU ID": "17074105",
    "Invoice Business Unit": "GRE OTHR SRV RES",
    Trade: "OTHER",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074106: {
    "BU ID": "17074106",
    "Invoice Business Unit": "GRE PLUM AOR COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074107: {
    "BU ID": "17074107",
    "Invoice Business Unit": "GRE PLUM AOR MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074108: {
    "BU ID": "17074108",
    "Invoice Business Unit": "GRE PLUM AOR RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "AOR",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074111: {
    "BU ID": "17074111",
    "Invoice Business Unit": "GRE PLUM MNT RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074112: {
    "BU ID": "17074112",
    "Invoice Business Unit": "GRE PLUM NCO COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074113: {
    "BU ID": "17074113",
    "Invoice Business Unit": "GRE PLUM NCO MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074114: {
    "BU ID": "17074114",
    "Invoice Business Unit": "GRE PLUM NCO RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074115: {
    "BU ID": "17074115",
    "Invoice Business Unit": "GRE PLUM SRV COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074116: {
    "BU ID": "17074116",
    "Invoice Business Unit": "GRE PLUM SRV MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074117: {
    "BU ID": "17074117",
    "Invoice Business Unit": "GRE PLUM SRV RES",
    Trade: "PLUM",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  35405856: {
    "BU ID": "35405856",
    "Invoice Business Unit": "GRE ADMN GEN OFF",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  900: {
    "BU ID": "900",
    "Invoice Business Unit": "Test Res HVAC Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  901: {
    "BU ID": "901",
    "Invoice Business Unit": "Plumbing - Install",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  926: {
    "BU ID": "926",
    "Invoice Business Unit": "Plumbing - Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  927: {
    "BU ID": "927",
    "Invoice Business Unit": "Plumbing - Maintenance",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  928: {
    "BU ID": "928",
    "Invoice Business Unit": "Plumbing - Sales",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  929: {
    "BU ID": "929",
    "Invoice Business Unit": "HVAC - Install",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  3864: {
    "BU ID": "3864",
    "Invoice Business Unit": "HVAC - Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  3865: {
    "BU ID": "3865",
    "Invoice Business Unit": "HVAC - Maintenance",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  3866: {
    "BU ID": "3866",
    "Invoice Business Unit": "HVAC - Sales",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  3867: {
    "BU ID": "3867",
    "Invoice Business Unit": "Imported Default Businessunit",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074097: {
    "BU ID": "17074097",
    "Invoice Business Unit": "GRE OTHR MNT COM",
    Trade: "OTHER",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074099: {
    "BU ID": "17074099",
    "Invoice Business Unit": "GRE OTHR MNT RES",
    Trade: "OTHER",
    Segment: "RESI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074100: {
    "BU ID": "17074100",
    "Invoice Business Unit": "GRE OTHR NCO COM",
    Trade: "OTHER",
    Segment: "COM",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074102: {
    "BU ID": "17074102",
    "Invoice Business Unit": "GRE OTHR NCO RES",
    Trade: "OTHER",
    Segment: "RESI",
    Type: "NCO",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074103: {
    "BU ID": "17074103",
    "Invoice Business Unit": "GRE OTHR SRV COM",
    Trade: "OTHER",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074109: {
    "BU ID": "17074109",
    "Invoice Business Unit": "GRE PLUM MNT COM",
    Trade: "PLUM",
    Segment: "COM",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  17074110: {
    "BU ID": "17074110",
    "Invoice Business Unit": "GRE PLUM MNT MFY",
    Trade: "PLUM",
    Segment: "MULTI",
    Type: "SER",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  30818702: {
    "BU ID": "30818702",
    "Invoice Business Unit": "GKB Test BU",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "PA",
    Name: "Parker-Arntz Plumbing & Heating, Inc.",
  },
  1034876: {
    "BU ID": "1034876",
    "Invoice Business Unit": "10EXP-Resid AOR",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "EXP",
    Name: "Expert Residential AOR",
  },
  1034877: {
    "BU ID": "1034877",
    "Invoice Business Unit": "20EXP-Resid NC",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "EXP",
    Name: "Expert Residential New Const",
  },
  1034878: {
    "BU ID": "1034878",
    "Invoice Business Unit": "30EXP-Comm AOR",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "EXP",
    Name: "Expert Commercial AOR",
  },
  1034879: {
    "BU ID": "1034879",
    "Invoice Business Unit": "40EXP-Comm NC",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "EXP",
    Name: "Expert Commercial New Constr",
  },
  1034880: {
    "BU ID": "1034880",
    "Invoice Business Unit": "50EXP-Resid Service",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Residential Service",
  },
  1034881: {
    "BU ID": "1034881",
    "Invoice Business Unit": "60EXP-Comm Service",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Commercial Service",
  },
  1034882: {
    "BU ID": "1034882",
    "Invoice Business Unit": "70EXP-OTC",
    Trade: "HVAC",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "Expert Over the Counter",
  },
  1034883: {
    "BU ID": "1034883",
    "Invoice Business Unit": "80EXP-Resid Maint",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Residential Maintenance",
  },
  1034884: {
    "BU ID": "1034884",
    "Invoice Business Unit": "90EXP-Comm Maint",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Commercial Maintenance",
  },
  1951850: {
    "BU ID": "1951850",
    "Invoice Business Unit": "EXP00-HEAD OFFICE",
    Trade: "HVAC",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "EXP00 HEAD OFFICE",
  },
  1951978: {
    "BU ID": "1951978",
    "Invoice Business Unit": "EXP01-ADMIN/OFFICE",
    Trade: "HVAC",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "EXP01-ADMINISTRATION/OFFICE",
  },
  55786506: {
    "BU ID": "55786506",
    "Invoice Business Unit": "51EST-Resid Service",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Residential Service",
  },
  55793158: {
    "BU ID": "55793158",
    "Invoice Business Unit": "11EST-Resid AOR",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "EXP",
    Name: "Expert Residential AOR",
  },
  55793418: {
    "BU ID": "55793418",
    "Invoice Business Unit": "61EST-Comm Service",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "EAST COMMERCIAL SERVICE",
  },
  55794188: {
    "BU ID": "55794188",
    "Invoice Business Unit": "81EST-Resid Maint",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "Expert Residential Maintenance",
  },
  63418507: {
    "BU ID": "63418507",
    "Invoice Business Unit": "31EST-Comm AOR",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "EXP",
    Name: "EAST COMMERCIAL AOR",
  },
  108709: {
    "BU ID": "108709",
    "Invoice Business Unit": "Imported Default Businessunit",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  1000004: {
    "BU ID": "1000004",
    "Invoice Business Unit": "Imported Businessunit",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  1034885: {
    "BU ID": "1034885",
    "Invoice Business Unit": "CTM-Commercial Time & Material",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  1034886: {
    "BU ID": "1034886",
    "Invoice Business Unit": "RES SERVIC-W/O Billings - Res Service",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  1034887: {
    "BU ID": "1034887",
    "Invoice Business Unit": "SVC.CONT-Service Contracts",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  1034888: {
    "BU ID": "1034888",
    "Invoice Business Unit": "UNAPP-Unapplied Receipts",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  1952106: {
    "BU ID": "1952106",
    "Invoice Business Unit": "EXP03-SHEET METAL SHOP",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "EXP03-SHEET METAL SHOP",
  },
  1952234: {
    "BU ID": "1952234",
    "Invoice Business Unit": "EXP04-FACILITY/BLDG",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "EXP04-FACILITY/BLDG",
  },
  1952362: {
    "BU ID": "1952362",
    "Invoice Business Unit": "EXP02-WAREHOUSE",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "EXP02-WAREHOUSE",
  },
  4078369: {
    "BU ID": "4078369",
    "Invoice Business Unit": "10-Residential AOR",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "EXP",
    Name: "",
  },
  4078370: {
    "BU ID": "4078370",
    "Invoice Business Unit": "20-Residential New Construction",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "EXP",
    Name: "",
  },
  4078371: {
    "BU ID": "4078371",
    "Invoice Business Unit": "30-Commercial AOR",
    Trade: "HVAC",
    Segment: "COM",
    Type: "AOR",
    Business: "EXP",
    Name: "",
  },
  4078372: {
    "BU ID": "4078372",
    "Invoice Business Unit": "40-Commercial New Construction",
    Trade: "HVAC",
    Segment: "COM",
    Type: "NCO",
    Business: "EXP",
    Name: "",
  },
  4078373: {
    "BU ID": "4078373",
    "Invoice Business Unit": "50-Residential Service",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "",
  },
  4078374: {
    "BU ID": "4078374",
    "Invoice Business Unit": "60-Commercial Service",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "",
  },
  4078375: {
    "BU ID": "4078375",
    "Invoice Business Unit": "70-Over the Counter Retail",
    Trade: "IMPT",
    Segment: "IMPT",
    Type: "IMPT",
    Business: "EXP",
    Name: "",
  },
  4078376: {
    "BU ID": "4078376",
    "Invoice Business Unit": "80-Residential Maintenance",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "SER",
    Business: "EXP",
    Name: "",
  },
  4078377: {
    "BU ID": "4078377",
    "Invoice Business Unit": "90-Commercial Maintenance",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "",
  },
  55794694: {
    "BU ID": "55794694",
    "Invoice Business Unit": "21EST-Resid NC",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "NCO",
    Business: "EXP",
    Name: "EST RESIDENTIAL NEW CONST",
  },
  55796230: {
    "BU ID": "55796230",
    "Invoice Business Unit": "91EST-Comm Maint",
    Trade: "HVAC",
    Segment: "COM",
    Type: "SER",
    Business: "EXP",
    Name: "EST COMMERCIAL MAINT",
  },
  79899215: {
    "BU ID": "79899215",
    "Invoice Business Unit": "12AA-Resid AOR",
    Trade: "HVAC",
    Segment: "RESI",
    Type: "AOR",
    Business: "EXP",
    Name: "Jetstream Residential AOR",
  },
};

module.exports = business_unit_data;
