const b_units = [
  {
    id: 473,
    active: false,
    name: "Plumbing - Install",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888888",
    invoiceHeader: "PinnacleMEP_template\n, \n",
    invoiceMessage: "Thank you for choosing PinnacleMEP_template",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a financing charge of 1% per month shall be applied for overdue amounts.",
    acknowledgementParagraph:
      "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "2023-02-09T17:15:57.1037685Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 475,
    active: false,
    name: "Plumbing - Service",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888888",
    invoiceHeader: "PinnacleMEP_template\n, \n",
    invoiceMessage: "Thank you for choosing PinnacleMEP_template",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a financing charge of 1% per month shall be applied for overdue amounts.",
    acknowledgementParagraph:
      "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "2023-02-09T17:15:57.462509Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 477,
    active: false,
    name: "Plumbing - Maintenance",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888888",
    invoiceHeader: "PinnacleMEP_template\n, \n",
    invoiceMessage: "Thank you for choosing PinnacleMEP_template",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a financing charge of 1% per month shall be applied for overdue amounts.",
    acknowledgementParagraph:
      "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "2023-02-09T17:15:57.78197Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 479,
    active: false,
    name: "Plumbing - Sales",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888888",
    invoiceHeader: "PinnacleMEP_template\n, \n",
    invoiceMessage: "Thank you for choosing PinnacleMEP_template",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a financing charge of 1% per month shall be applied for overdue amounts.",
    acknowledgementParagraph:
      "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "2023-02-09T17:15:58.120643Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 493,
    active: false,
    name: "HVAC - Install",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888888",
    invoiceHeader: "PinnacleMEP_template\n, \n",
    invoiceMessage: "Thank you for choosing PinnacleMEP_template",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a financing charge of 1% per month shall be applied for overdue amounts.",
    acknowledgementParagraph:
      "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "2023-02-09T17:15:58.5551111Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 494,
    active: false,
    name: "HVAC - Service",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888888",
    invoiceHeader: "PinnacleMEP_template\n, \n",
    invoiceMessage: "Thank you for choosing PinnacleMEP_template",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a financing charge of 1% per month shall be applied for overdue amounts.",
    acknowledgementParagraph:
      "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "2023-02-09T17:15:58.8042886Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 495,
    active: false,
    name: "HVAC - Maintenance",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888888",
    invoiceHeader: "PinnacleMEP_template\n, \n",
    invoiceMessage: "Thank you for choosing PinnacleMEP_template",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a financing charge of 1% per month shall be applied for overdue amounts.",
    acknowledgementParagraph:
      "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "2023-02-09T17:15:59.0615354Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 496,
    active: false,
    name: "HVAC - Sales",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888888",
    invoiceHeader: "PinnacleMEP_template\n, \n",
    invoiceMessage: "Thank you for choosing PinnacleMEP_template",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a financing charge of 1% per month shall be applied for overdue amounts.",
    acknowledgementParagraph:
      "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "2023-02-09T17:15:59.3181175Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 102565,
    active: false,
    name: "Imported Default Businessunit",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: null,
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical\n4537 North Franklin Road \nIndianapolis, IN 46226",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T13:45:09.115086Z",
    externalData: null,
  },
  {
    id: 2043104,
    active: true,
    name: "SFT HVAC AOR COM",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:49.9655662Z",
    externalData: null,
  },
  {
    id: 2043105,
    active: true,
    name: "SFT HVAC AOR MFY",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.1290311Z",
    externalData: null,
  },
  {
    id: 2043106,
    active: true,
    name: "SFT HVAC AOR RES",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.1589134Z",
    externalData: null,
  },
  {
    id: 2043107,
    active: true,
    name: "SFT HVAC MNT COM",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.1814148Z",
    externalData: null,
  },
  {
    id: 2043108,
    active: true,
    name: "SFT HVAC MNT MFY",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.2195112Z",
    externalData: null,
  },
  {
    id: 2043109,
    active: true,
    name: "SFT HVAC MNT RES",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.2384567Z",
    externalData: null,
  },
  {
    id: 2043110,
    active: true,
    name: "SFT HVAC NCO COM",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.2570889Z",
    externalData: null,
  },
  {
    id: 2043111,
    active: true,
    name: "SFT HVAC NCO MFY",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.2757462Z",
    externalData: null,
  },
  {
    id: 2043112,
    active: true,
    name: "SFT HVAC NCO RES",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.2974992Z",
    externalData: null,
  },
  {
    id: 2043113,
    active: true,
    name: "SFT HVAC SRV COM",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.3182315Z",
    externalData: null,
  },
  {
    id: 2043114,
    active: true,
    name: "SFT HVAC SRV MFY",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.3488655Z",
    externalData: null,
  },
  {
    id: 2043115,
    active: true,
    name: "SFT HVAC SRV RES",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "3175475355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: "Thank you for choosing Swift Air Mechanical!",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-29T20:30:50.396228Z",
    externalData: null,
  },
  {
    id: 2043116,
    active: false,
    name: "LOC OTHR AOR COM",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888913",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043117,
    active: false,
    name: "LOC OTHR AOR MFY",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888915",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043118,
    active: false,
    name: "LOC OTHR AOR RES",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888914",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043119,
    active: false,
    name: "LOC OTHR MNT COM",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888919",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043120,
    active: false,
    name: "LOC OTHR MNT MFY",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888921",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043121,
    active: false,
    name: "LOC OTHR MNT RES",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888920",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043122,
    active: false,
    name: "LOC OTHR NCO COM",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888916",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043123,
    active: false,
    name: "LOC OTHR NCO MFY",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888918",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043124,
    active: false,
    name: "LOC OTHR NCO RES",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888917",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043125,
    active: false,
    name: "LOC OTHR SRV COM",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888922",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043126,
    active: false,
    name: "LOC OTHR SRV MFY",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888924",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043127,
    active: false,
    name: "LOC OTHR SRV RES",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888923",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043128,
    active: false,
    name: "LOC PLUM AOR COM",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888901",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043129,
    active: false,
    name: "LOC PLUM AOR MFY",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888903",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043130,
    active: false,
    name: "LOC PLUM AOR RES",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888902",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043131,
    active: false,
    name: "LOC PLUM MNT COM",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888907",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043132,
    active: false,
    name: "LOC PLUM MNT MFY",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888909",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043133,
    active: false,
    name: "LOC PLUM MNT RES",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888908",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043134,
    active: false,
    name: "LOC PLUM NCO COM",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888904",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043135,
    active: false,
    name: "LOC PLUM NCO MFY",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888906",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043136,
    active: false,
    name: "LOC PLUM NCO RES",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888905",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 2043137,
    active: false,
    name: "LOC PLUM SRV COM",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888910",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-27T16:48:42.5631408Z",
    externalData: null,
  },
  {
    id: 2043138,
    active: false,
    name: "LOC PLUM SRV MFY",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888912",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-27T16:48:42.5548178Z",
    externalData: null,
  },
  {
    id: 2043139,
    active: false,
    name: "LOC PLUM SRV RES",
    officialName: "PinnacleMEP_template",
    email: "noemail@noemail.com",
    currency: "USD",
    phoneNumber: "8888888911",
    invoiceHeader: null,
    invoiceMessage: "Thank you for choosing {official name}",
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {Business Unit Official Name}  to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-27T16:48:42.508551Z",
    externalData: null,
  },
  {
    id: 12041793,
    active: false,
    name: "Perdue",
    officialName: "Perdue",
    email: null,
    currency: null,
    phoneNumber: null,
    invoiceHeader: null,
    invoiceMessage: null,
    defaultTaxRate: 0.0,
    authorizationParagraph: null,
    acknowledgementParagraph: null,
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 12041794,
    active: false,
    name: "Swift Air",
    officialName: "Swift Air",
    email: null,
    currency: null,
    phoneNumber: null,
    invoiceHeader: null,
    invoiceMessage: null,
    defaultTaxRate: 0.0,
    authorizationParagraph: null,
    acknowledgementParagraph: null,
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 12041795,
    active: false,
    name: "Perdue:Service",
    officialName: "Perdue:Service",
    email: null,
    currency: null,
    phoneNumber: null,
    invoiceHeader: null,
    invoiceMessage: null,
    defaultTaxRate: 0.0,
    authorizationParagraph: null,
    acknowledgementParagraph: null,
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 12041796,
    active: false,
    name: "Perdue:Installation",
    officialName: "Perdue:Installation",
    email: null,
    currency: null,
    phoneNumber: null,
    invoiceHeader: null,
    invoiceMessage: null,
    defaultTaxRate: 0.0,
    authorizationParagraph: null,
    acknowledgementParagraph: null,
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 12041797,
    active: false,
    name: "Swift Air:Service",
    officialName: "Swift Air:Service",
    email: null,
    currency: null,
    phoneNumber: null,
    invoiceHeader: null,
    invoiceMessage: null,
    defaultTaxRate: 0.0,
    authorizationParagraph: null,
    acknowledgementParagraph: null,
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 12041798,
    active: false,
    name: "Swift Air:SA-Installation",
    officialName: "Swift Air:SA-Installation",
    email: null,
    currency: null,
    phoneNumber: null,
    invoiceHeader: null,
    invoiceMessage: null,
    defaultTaxRate: 0.0,
    authorizationParagraph: null,
    acknowledgementParagraph: null,
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 12041799,
    active: false,
    name: "Perdue:Home Performance",
    officialName: "Perdue:Home Performance",
    email: null,
    currency: null,
    phoneNumber: null,
    invoiceHeader: null,
    invoiceMessage: null,
    defaultTaxRate: 0.0,
    authorizationParagraph: null,
    acknowledgementParagraph: null,
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 12041800,
    active: false,
    name: "Office",
    officialName: "Office",
    email: null,
    currency: null,
    phoneNumber: null,
    invoiceHeader: null,
    invoiceMessage: null,
    defaultTaxRate: 0.0,
    authorizationParagraph: null,
    acknowledgementParagraph: null,
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 12041801,
    active: false,
    name: "Perdue:Home Performance:COMFORT SPECIALIST",
    officialName: "Perdue:Home Performance:COMFORT SPECIALIST",
    email: null,
    currency: null,
    phoneNumber: null,
    invoiceHeader: null,
    invoiceMessage: null,
    defaultTaxRate: 0.0,
    authorizationParagraph: null,
    acknowledgementParagraph: null,
    address: {
      street: null,
      unit: null,
      city: null,
      state: null,
      zip: null,
      country: null,
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "0001-01-01T00:00:00Z",
    modifiedOn: "2024-04-16T17:47:21.4137102Z",
    externalData: null,
  },
  {
    id: 57003194,
    active: true,
    name: "SFT ADMN GEN OFF",
    officialName: "Swift Air Mechanical",
    email: "office@swiftairindy.com",
    currency: "USD",
    phoneNumber: "(317) 547-5355",
    invoiceHeader:
      "Swift Air Mechanical, LLC \n8740 E 30th Street \nIndianapolis, IN 46219",
    invoiceMessage: null,
    defaultTaxRate: 0.0,
    authorizationParagraph:
      "I hereby authorize {BusinessUnitOfficialName} to complete the above work in the amount of {Total} to be performed.",
    acknowledgementParagraph:
      "I have inspected all of the work done by {TechnicianName}. I find that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor pursuant to the contract as agreed.",
    address: {
      street: "4537 North Franklin Road",
      unit: null,
      city: "Indianapolis",
      state: "IN",
      zip: "46226",
      country: "USA",
    },
    materialSku: null,
    quickbooksClass: null,
    accountCode: null,
    franchiseId: null,
    conceptCode: "NotSet",
    corporateContractNumber: null,
    tenant: {
      id: 2450322465,
      name: "swiftairmechanicalllc",
      accountCode: null,
      franchiseId: null,
      conceptCode: "NotSet",
      modifiedOn: "2024-05-08T05:45:27.660666Z",
    },
    createdOn: "2024-05-08T18:08:35.3647831Z",
    modifiedOn: "2024-05-08T18:08:35.9357921Z",
    externalData: null,
  },
];

const csv_generator = require("./modules/csv_generator");
const find_lenghthiest_header = require("./modules/find_lengthiest_header");

async function main() {
  // find lengthiest data
  const flattenedSampleObj = await find_lenghthiest_header(b_units);

  await csv_generator(b_units, flattenedSampleObj, "SFT_business_units");
}

main();
