const data = [
  {
    active: "null",
    id: 33544886,
    syncStatus: "Exported",
    summary: "null",
    referenceNumber: "null",
    invoiceDate: "1900-01-01T00:00:00Z",
    dueDate: "1900-01-01T00:00:00Z",
    subTotal: "0.00",
    salesTax: "0.00",
    salesTaxCode: "null",
    total: "0.00",
    balance: "0.00",
    invoiceType: "null",
    customerid: 32170776,
    customername: "ADDINGTON PLACE",
    customerAddressstreet: "42102 SEVEN MILE RD.",
    customerAddressunit: "null",
    customerAddresscity: "NORTHVILLE, MI",
    customerAddressstate: "null",
    customerAddresszip: "48167",
    customerAddresscountry: "null",
    locationid: 32271756,
    locationname: "ADDINGTON PLACE",
    locationAddressstreet: "42102 SEVEN MILE RD.",
    locationAddressunit: "null",
    locationAddresscity: "NORTHVILLE, MI",
    locationAddressstate: "null",
    locationAddresszip: "48167",
    locationAddresscountry: "null",
    businessUnitid: 1034881,
    businessUnitname: "60EXP-Comm Service",
    termName: "Due Upon Receipt",
    createdBy: "null",
    batch: "null",
    depositedOn: "null",
    createdOn: "1951-01-01T00:00:00Z",
    modifiedOn: "2022-07-11T23:37:04.33Z",
    adjustmentToId: "null",
    jobid: 32407039,
    jobnumber: "0004137",
    jobtype: "Imported JobType",
    projectId: "null",
    royaltystatus: "Pending",
    royaltydate: "null",
    royaltysentOn: "null",
    royaltymemo: "null",
    employeeInfo: "null",
    commissionEligibilityDate: "null",
    items: "null",
    customFields: "null",
  },
  {
    active: true,
    id: 33544887,
    syncStatus: "Exported",
    summary: "null",
    referenceNumber: "null",
    invoiceDate: "1900-01-01T00:00:00Z",
    dueDate: "1900-01-01T00:00:00Z",
    subTotal: "0.00",
    salesTax: "0.00",
    salesTaxCode: "null",
    total: "0.00",
    balance: "0.00",
    invoiceType: "null",
    customerid: 32170776,
    customername: "ADDINGTON PLACE",
    customerAddressstreet: "42102 SEVEN MILE RD.",
    customerAddressunit: "null",
    customerAddresscity: "NORTHVILLE, MI",
    customerAddressstate: "null",
    customerAddresszip: "48167",
    customerAddresscountry: "null",
    locationid: 32271756,
    locationname: "ADDINGTON PLACE",
    locationAddressstreet: "42102 SEVEN MILE RD.",
    locationAddressunit: "null",
    locationAddresscity: "NORTHVILLE, MI",
    locationAddressstate: "null",
    locationAddresszip: "48167",
    locationAddresscountry: "null",
    businessUnitid: 1034881,
    businessUnitname: "60EXP-Comm Service",
    termName: "Due Upon Receipt",
    createdBy: "null",
    batch: "null",
    depositedOn: "null",
    createdOn: "1951-01-01T00:00:00Z",
    modifiedOn: "2022-07-11T23:37:04.33Z",
    adjustmentToId: "null",
    jobid: 32407040,
    jobnumber: "0004137",
    jobtype: "Imported JobType",
    projectId: "null",
    royaltystatus: "Pending",
    royaltydate: "null",
    royaltysentOn: "null",
    royaltymemo: "null",
    employeeInfo: "null",
    commissionEligibilityDate: "null",
    items: "null",
    customFields: "null",
  },
  {
    active: true,
    id: 33544888,
    syncStatus: "Exported",
    summary: "null",
    referenceNumber: "null",
    invoiceDate: "1900-01-01T00:00:00Z",
    dueDate: "1900-01-01T00:00:00Z",
    subTotal: "0.00",
    salesTax: "0.00",
    salesTaxCode: "null",
    total: "0.00",
    balance: "0.00",
    invoiceType: "null",
    customerid: 32208394,
    customername: "NCS CONSTRUCTION-MAIN OFFICE",
    customerAddressstreet: "876 Horace Brown Drive",
    customerAddressunit: "null",
    customerAddresscity: "Madison Heights",
    customerAddressstate: "MI",
    customerAddresszip: "48071",
    customerAddresscountry: "USA",
    locationid: 32229352,
    locationname: "ZOYO YOGORT",
    locationAddressstreet: "3067 ROCHESTER RD.",
    locationAddressunit: "null",
    locationAddresscity: "TROY, MI",
    locationAddressstate: "null",
    locationAddresszip: "48063",
    locationAddresscountry: "null",
    businessUnitid: 1034881,
    businessUnitname: "60EXP-Comm Service",
    termName: "Due Upon Receipt",
    createdBy: "null",
    batch: "null",
    depositedOn: "null",
    createdOn: "1951-01-01T00:00:00Z",
    modifiedOn: "2022-07-11T23:37:04.33Z",
    adjustmentToId: "null",
    jobid: 32407041,
    jobnumber: "0004201",
    jobtype: "Imported JobType",
    projectId: "null",
    royaltystatus: "Pending",
    royaltydate: "null",
    royaltysentOn: "null",
    royaltymemo: "null",
    employeeInfo: "null",
    commissionEligibilityDate: "null",
    items: "null",
    customFields: "null",
  },
];

const fs = require("fs");
const createCsvWriter = require("csv-writer").createObjectCsvWriter;

// Define the CSV file path
const csvFilePath = "invoice.csv";

// Create a CSV writer with headers auto-generated from the object properties
const csvWriter = createCsvWriter({
  path: csvFilePath,
  header: [
    { id: 'active', title: 'active' },
    { id: 'id', title: 'id' },
    { id: 'syncStatus', title: 'syncStatus' },
    { id: 'summary', title: 'summary' },
    { id: 'referenceNumber', title: 'referenceNumber' },
    { id: 'invoiceDate', title: 'invoiceDate' },
    { id: 'dueDate', title: 'dueDate' },
    { id: 'subTotal', title: 'subTotal' },
    { id: 'salesTax', title: 'salesTax' },
    { id: 'salesTaxCode', title: 'salesTaxCode' },
    { id: 'total', title: 'total' },
    { id: 'balance', title: 'balance' },
    { id: 'invoiceType', title: 'invoiceType' },
    { id: 'customerid', title: 'customerid' },
    { id: 'customername', title: 'customername' },
    { id: 'customerAddressstreet', title: 'customerAddressstreet' },
    { id: 'customerAddressunit', title: 'customerAddressunit' },
    { id: 'customerAddresscity', title: 'customerAddresscity' },
    { id: 'customerAddressstate', title: 'customerAddressstate' },
    { id: 'customerAddresszip', title: 'customerAddresszip' },
    { id: 'customerAddresscountry', title: 'customerAddresscountry' },
    { id: 'locationid', title: 'locationid' },
    { id: 'locationname', title: 'locationname' },
    { id: 'locationAddressstreet', title: 'locationAddressstreet' },
    { id: 'locationAddressunit', title: 'locationAddressunit' },
    { id: 'locationAddresscity', title: 'locationAddresscity' },
    { id: 'locationAddressstate', title: 'locationAddressstate' },
    { id: 'locationAddresszip', title: 'locationAddresszip' },
    { id: 'locationAddresscountry', title: 'locationAddresscountry' },
    { id: 'businessUnitid', title: 'businessUnitid' },
    { id: 'businessUnitname', title: 'businessUnitname' },
    { id: 'termName', title: 'termName' },
    { id: 'createdBy', title: 'createdBy' },
    { id: 'batch', title: 'batch' },
    { id: 'depositedOn', title: 'depositedOn' },
    { id: 'createdOn', title: 'createdOn' },
    { id: 'modifiedOn', title: 'modifiedOn' },
    { id: 'adjustmentToId', title: 'adjustmentToId' },
    { id: 'jobid', title: 'jobid' },
    { id: 'jobnumber', title: 'jobnumber' },
    { id: 'jobtype', title: 'jobtype' },
    { id: 'projectId', title: 'projectId' },
    { id: 'royaltystatus', title: 'royaltystatus' },
    { id: 'royaltydate', title: 'royaltydate' },
    { id: 'royaltysentOn', title: 'royaltysentOn' },
    { id: 'royaltymemo', title: 'royaltymemo' },
    { id: 'employeeInfo', title: 'employeeInfo' },
    {
      id: 'commissionEligibilityDate',
      title: 'commissionEligibilityDate'
    },
    { id: 'items', title: 'items' },
    { id: 'customFields', title: 'customFields' }
  ],
  append: false, // Set to false to overwrite the file; true to append
});

// Write the data to the CSV file
csvWriter
  .writeRecords(data)
  .then(() => {
    console.log("Data has been written to the CSV file.");
  })
  .catch((error) => {
    console.error("Error writing data to the CSV file:", error);
  });
