// const api_collection = [
//   {
//     api_group: "accounting",
//     api_name: "invoices",
//     mode: "items",
//   },
//   {
//     api_group: "inventory",
//     api_name: "adjustments",
//     mode: "items",
//   },
//   {
//     api_group: "inventory",
//     api_name: "transfers",
//     mode: "items",
//   },
//   {
//     api_group: "accounting",
//     api_name: "invoices",
//   },
//   {
//     api_group: "accounting",
//     api_name: "inventory-bills",
//   },
//   {
//     api_group: "accounting",
//     api_name: "payments",
//   },
//   {
//     api_group: "accounting",
//     api_name: "ap-payments",
//   },
//   {
//     api_group: "accounting",
//     api_name: "journal-entries",
//   },
//   {
//     api_group: "accounting",
//     api_name: "payment-terms",
//   },
//   {
//     api_group: "accounting",
//     api_name: "payment-types",
//   },
//   {
//     api_group: "accounting",
//     api_name: "tax-zones",
//   },
//   {
//     api_group: "crm",
//     api_name: "customers",
//   },
//   {
//     api_group: "crm",
//     api_name: "bookings",
//   },
//   {
//     api_group: "crm",
//     api_name: "locations",
//   },
//   {
//     api_group: "crm",
//     api_name: "booking-provider-tags",
//   },
//   {
//     api_group: "crm",
//     api_name: "leads",
//   },
//   {
//     api_group: "dispatch",
//     api_name: "appointment-assignments",
//   },
//   {
//     api_group: "dispatch",
//     api_name: "zones",
//   },
//   {
//     api_group: "dispatch",
//     api_name: "non-job-appointments",
//   },
//   {
//     api_group: "dispatch",
//     api_name: "teams",
//   },
//   {
//     api_group: "dispatch",
//     api_name: "technician-shifts",
//   },
//   {
//     api_group: "equipmentsystems",
//     api_name: "installed-equipment",
//   },
//   {
//     api_group: "inventory",
//     api_name: "adjustments",
//   },
//   {
//     api_group: "inventory",
//     api_name: "transfers",
//   },
//   {
//     api_group: "inventory",
//     api_name: "purchase-orders",
//   },
//   {
//     api_group: "inventory",
//     api_name: "receipts",
//   },
//   {
//     api_group: "inventory",
//     api_name: "returns",
//   },
//   {
//     api_group: "inventory",
//     api_name: "trucks",
//   },
//   {
//     api_group: "inventory",
//     api_name: "vendors",
//   },
//   {
//     api_group: "inventory",
//     api_name: "warehouses",
//   },
//   {
//     api_group: "inventory",
//     api_name: "purchase-order-markups",
//   },
//   {
//     api_group: "inventory",
//     api_name: "purchase-order-types",
//   },
//   {
//     api_group: "jbce",
//     api_name: "call-reasons",
//   },
//   {
//     api_group: "jpm",
//     api_name: "appointments", // end keyword is used in this api response
//   },
//   {
//     api_group: "jpm",
//     api_name: "job-types",
//   },
//   {
//     api_group: "jpm",
//     api_name: "jobs",
//   },
//   {
//     api_group: "jpm",
//     api_name: "projects",
//   },
//   {
//     api_group: "jpm",
//     api_name: "job-cancel-reasons",
//   },
//   {
//     api_group: "jpm",
//     api_name: "job-hold-reasons",
//   },
//   {
//     api_group: "jpm",
//     api_name: "project-statuses",
//   },
//   {
//     api_group: "jpm",
//     api_name: "project-substatuses",
//   },
//   {
//     api_group: "marketing",
//     api_name: "campaigns",
//   },
//   {
//     api_group: "marketing",
//     api_name: "categories",
//   },
//   {
//     api_group: "marketing",
//     api_name: "suppressions",
//   },
//   {
//     api_group: "marketing",
//     api_name: "costs",
//   },
//   {
//     api_group: "marketingreputation",
//     api_name: "reviews",
//   },
//   {
//     api_group: "memberships",
//     api_name: "memberships",
//   },
//   {
//     api_group: "memberships",
//     api_name: "recurring-services",
//   },
//   {
//     api_group: "memberships",
//     api_name: "recurring-service-events",
//   },
//   {
//     api_group: "memberships",
//     api_name: "recurring-service-types",
//   },
//   {
//     api_group: "memberships",
//     api_name: "membership-types",
//   },
//   {
//     api_group: "payroll",
//     api_name: "payrolls",
//   },
//   {
//     api_group: "payroll",
//     api_name: "payroll-adjustments",
//   },
//   {
//     api_group: "payroll",
//     api_name: "gross-pay-items",
//   },
//   {
//     api_group: "payroll",
//     api_name: "jobs/splits",
//   },
//   {
//     api_group: "payroll",
//     api_name: "jobs/timesheets",
//   },
//   {
//     api_group: "payroll",
//     api_name: "timesheet-codes",
//   },
//   {
//     api_group: "payroll",
//     api_name: "activity-codes",
//   },
//   {
//     api_group: "payroll",
//     api_name: "locations/rates",
//   },
//   {
//     api_group: "payroll",
//     api_name: "non-job-timesheets",
//   },
//   {
//     api_group: "pricebook",
//     api_name: "categories",
//   },
//   {
//     api_group: "pricebook",
//     api_name: "equipment",
//   },
//   {
//     api_group: "pricebook",
//     api_name: "materials",
//   },
//   {
//     api_group: "pricebook",
//     api_name: "discounts-and-fees",
//   },
//   {
//     api_group: "pricebook",
//     api_name: "images",
//   },
//   {
//     api_group: "pricebook",
//     api_name: "services",
//   },
//   {
//     api_group: "pricebook",
//     api_name: "materialsmarkup",
//   },
//   {
//     api_group: "reporting",
//     api_name: "report-categories",
//   },
//   {
//     api_group: "sales",
//     api_name: "estimates",
//   },
//   {
//     api_group: "sales",
//     api_name: "estimates/export",
//   },
//   {
//     api_group: "sales",
//     api_name: "estimates/items",
//   },
//   {
//     api_group: "service-agreements",
//     api_name: "service-agreements",
//   },
//   {
//     api_group: "settings",
//     api_name: "business-units",
//   },
//   {
//     api_group: "settings",
//     api_name: "employees",
//   },
//   {
//     api_group: "settings",
//     api_name: "technicians",
//   },
//   {
//     api_group: "settings",
//     api_name: "tag-types",
//   },
//   {
//     api_group: "settings",
//     api_name: "user-roles",
//   },
//   {
//     api_group: "taskmanagement",
//     api_name: "data",
//   },
//   {
//     api_group: "telecom",
//     api_name: "export/calls",
//   },
//   {
//     api_group: "telecom",
//     api_name: "calls",
//   },
//   {
//     api_group: "forms",
//     api_name: "forms",
//   },
//   {
//     api_group: "forms",
//     api_name: "submissions",
//   },
// ];

// const fs = require("fs");

// try {
//   const data = fs.readFileSync("./modules/hvac_schema.sql", "utf-8");
//   console.log(data);
// } catch (error) {
//   console.error("Error reading the file:", error);
// }

const kpi_data = [
  {
    "BU ID": 1951850,
    "Business Units Name": "EXP00-HEAD OFFICE",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 1951978,
    "Business Units Name": "EXP01-ADMIN/OFFICE",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 1952362,
    "Business Units Name": "EXP02-WAREHOUSE",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 1952106,
    "Business Units Name": "EXP03-SHEET METAL SHOP",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 1952234,
    "Business Units Name": "EXP04-FACILITY/BLDG",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 1034878,
    "Business Units Name": "30EXP-Comm AOR",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 1034884,
    "Business Units Name": "90EXP-Comm Maint",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 1034879,
    "Business Units Name": "40EXP-Comm NC",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 1034881,
    "Business Units Name": "60EXP-Comm Service",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 1034882,
    "Business Units Name": "70EXP-OTC",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 1034876,
    "Business Units Name": "10EXP-Resid AOR",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 55793158,
    "Business Units Name": "11EST-Resid AOR",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 1034883,
    "Business Units Name": "80EXP-Resid Maint",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 55794188,
    "Business Units Name": "81EST-Resid Maint",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 1034877,
    "Business Units Name": "20EXP-Resid NC",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 1034880,
    "Business Units Name": "50EXP-Resid Service",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 55786506,
    "Business Units Name": "51EST-Resid Service",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 108709,
    "Business Units Name": "Imported Default Businessunit",
    "Trade Type": "HIS",
    "Revenue Type": "HIS",
    "Account Type": "HIS",
  },
  {
    "BU ID": 1000004,
    "Business Units Name": "Imported Businessunit",
    "Trade Type": "HIS",
    "Revenue Type": "HIS",
    "Account Type": "HIS",
  },
  {
    "BU ID": 898,
    "Business Units Name": "GRE HVAC AOR RES",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 899,
    "Business Units Name": "GRE HVAC MNT COM",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 112805,
    "Business Units Name": "GRE HVAC AOR COM",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 9722674,
    "Business Units Name": "GRE HVAC AOR MFY",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074086,
    "Business Units Name": "GRE HVAC MNT MFY",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074087,
    "Business Units Name": "GRE HVAC MNT RES",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074088,
    "Business Units Name": "GRE HVAC NCO COM",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 17074089,
    "Business Units Name": "GRE HVAC NCO MFY",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074090,
    "Business Units Name": "GRE HVAC NCO RES",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074091,
    "Business Units Name": "GRE HVAC SRV COM",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 17074092,
    "Business Units Name": "GRE HVAC SRV MFY",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074093,
    "Business Units Name": "GRE HVAC SRV RES",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074094,
    "Business Units Name": "GRE OTHR AOR COM",
    "Trade Type": "OTHR",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074095,
    "Business Units Name": "GRE OTHR AOR MFY",
    "Trade Type": "OTHR",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074096,
    "Business Units Name": "GRE OTHR AOR RES",
    "Trade Type": "OTHR",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074097,
    "Business Units Name": "GRE OTHR MNT COM",
    "Trade Type": "OTHR",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 17074098,
    "Business Units Name": "GRE OTHR MNT MFY",
    "Trade Type": "OTHR",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074099,
    "Business Units Name": "GRE OTHR MNT RES",
    "Trade Type": "OTHR",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074100,
    "Business Units Name": "GRE OTHR NCO COM",
    "Trade Type": "OTHR",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 17074101,
    "Business Units Name": "GRE OTHR NCO MFY",
    "Trade Type": "OTHR",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074102,
    "Business Units Name": "GRE OTHR NCO RES",
    "Trade Type": "OTHR",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074103,
    "Business Units Name": "GRE OTHR SRV COM",
    "Trade Type": "OTHR",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 17074104,
    "Business Units Name": "GRE OTHR SRV MFY",
    "Trade Type": "OTHR",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074105,
    "Business Units Name": "GRE OTHR SRV RES",
    "Trade Type": "OTHR",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074106,
    "Business Units Name": "GRE PLUM AOR COM",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 17074107,
    "Business Units Name": "GRE PLUM AOR MFY",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074108,
    "Business Units Name": "GRE PLUM AOR RES",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074109,
    "Business Units Name": "GRE PLUM MNT COM",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 17074110,
    "Business Units Name": "GRE PLUM MNT MFY",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074111,
    "Business Units Name": "GRE PLUM MNT RES",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074112,
    "Business Units Name": "GRE PLUM NCO COM",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 17074113,
    "Business Units Name": "GRE PLUM NCO MFY",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074114,
    "Business Units Name": "GRE PLUM NCO RES",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074115,
    "Business Units Name": "GRE PLUM SRV COM",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 17074116,
    "Business Units Name": "GRE PLUM SRV MFY",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 17074117,
    "Business Units Name": "GRE PLUM SRV RES",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 35405856,
    "Business Units Name": "GRE ADMN GEN OFF",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 51353626,
    "Business Units Name": "FHC ADMN GEN OFF",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 13107277,
    "Business Units Name": "FAM PLUM SRV COM",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107279,
    "Business Units Name": "FAM PLUM SRV RES",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 11152547,
    "Business Units Name": "FAM HVAC AOR COM",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107264,
    "Business Units Name": "FAM HVAC AOR RES",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107265,
    "Business Units Name": "FAM HVAC MNT COM",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107267,
    "Business Units Name": "FAM HVAC MNT RES",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107268,
    "Business Units Name": "FAM HVAC SRV COM",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107270,
    "Business Units Name": "FAM HVAC SRV RES",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107271,
    "Business Units Name": "FAM PLUM AOR COM",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107273,
    "Business Units Name": "FAM PLUM AOR RES",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107274,
    "Business Units Name": "FAM PLUM MNT COM",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107276,
    "Business Units Name": "FAM PLUM MNT RES",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118462,
    "Business Units Name": "FAM ADMN GEN OFF",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 16118463,
    "Business Units Name": "FAM HVAC NCO COM",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118464,
    "Business Units Name": "FAM HVAC NCO RES",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118465,
    "Business Units Name": "FAM PLUM NCO COM",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118466,
    "Business Units Name": "FAM PLUM NCO RES",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 11156773,
    "Business Units Name": "SPR HVAC AOR COM",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107306,
    "Business Units Name": "SPR HVAC AOR RES",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107307,
    "Business Units Name": "SPR HVAC MNT COM",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107309,
    "Business Units Name": "SPR HVAC MNT RES",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107310,
    "Business Units Name": "SPR HVAC SRV COM",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107312,
    "Business Units Name": "SPR HVAC SRV RES",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107313,
    "Business Units Name": "SPR PLUM AOR COM",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107315,
    "Business Units Name": "SPR PLUM AOR RES",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107316,
    "Business Units Name": "SPR PLUM MNT COM",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107318,
    "Business Units Name": "SPR PLUM MNT RES",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107319,
    "Business Units Name": "SPR PLUM SRV COM",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107321,
    "Business Units Name": "SPR PLUM SRV RES",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118485,
    "Business Units Name": "SPR ADMN GEN OFF",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 16118486,
    "Business Units Name": "SPR HVAC NCO COM",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118487,
    "Business Units Name": "SPR HVAC NCO RES",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118488,
    "Business Units Name": "SPR PLUM NCO COM",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118489,
    "Business Units Name": "SPR PLUM NCO RES",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 11156642,
    "Business Units Name": "HAN HVAC AOR COM",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107281,
    "Business Units Name": "HAN HVAC AOR RES",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107282,
    "Business Units Name": "HAN HVAC MNT COM",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107284,
    "Business Units Name": "HAN HVAC MNT RES",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107285,
    "Business Units Name": "HAN HVAC SRV COM",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107287,
    "Business Units Name": "HAN HVAC SRV RES",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107288,
    "Business Units Name": "HAN PLUM AOR COM",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107290,
    "Business Units Name": "HAN PLUM AOR RES",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107291,
    "Business Units Name": "HAN PLUM MNT COM",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107293,
    "Business Units Name": "HAN PLUM MNT RES",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107294,
    "Business Units Name": "HAN PLUM SRV COM",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107296,
    "Business Units Name": "HAN PLUM SRV RES",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118467,
    "Business Units Name": "HAN ADMN GEN OFF",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 16118468,
    "Business Units Name": "HAN HVAC NCO COM",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118469,
    "Business Units Name": "HAN HVAC NCO RES",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118470,
    "Business Units Name": "HAN PLUM NCO COM",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118471,
    "Business Units Name": "HAN PLUM NCO RES",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 166181,
    "Business Units Name": "Imported Default Businessunit",
    "Trade Type": "HIS",
    "Revenue Type": "HIS",
    "Account Type": "HIS",
  },
  {
    "BU ID": 11157153,
    "Business Units Name": "KNL HVAC NCO COM",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107298,
    "Business Units Name": "KNL HVAC NCO RES",
    "Trade Type": "HVAC",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 13107302,
    "Business Units Name": "KNL PLUM NCO COM",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "COMM",
  },
  {
    "BU ID": 13107304,
    "Business Units Name": "KNL PLUM NCO RES",
    "Trade Type": "PLUM",
    "Revenue Type": "NCO",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118472,
    "Business Units Name": "KNL ADMN GEN OFF",
    "Trade Type": "EXP",
    "Revenue Type": "EXP",
    "Account Type": "EXP",
  },
  {
    "BU ID": 16118473,
    "Business Units Name": "KNL HVAC AOR COM",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118474,
    "Business Units Name": "KNL HVAC AOR RES",
    "Trade Type": "HVAC",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118475,
    "Business Units Name": "KNL HVAC MNT COM",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118476,
    "Business Units Name": "KNL HVAC MNT RES",
    "Trade Type": "HVAC",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118477,
    "Business Units Name": "KNL HVAC SRV COM",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118478,
    "Business Units Name": "KNL HVAC SRV RES",
    "Trade Type": "HVAC",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118479,
    "Business Units Name": "KNL PLUM AOR COM",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118480,
    "Business Units Name": "KNL PLUM AOR RES",
    "Trade Type": "PLUM",
    "Revenue Type": "AOR",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118481,
    "Business Units Name": "KNL PLUM MNT COM",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118482,
    "Business Units Name": "KNL PLUM MNT RES",
    "Trade Type": "PLUM",
    "Revenue Type": "MNT",
    "Account Type": "RES",
  },
  {
    "BU ID": 16118483,
    "Business Units Name": "KNL PLUM SRV COM",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "COMM",
  },
  {
    "BU ID": 16118484,
    "Business Units Name": "KNL PLUM SRV RES",
    "Trade Type": "PLUM",
    "Revenue Type": "SER",
    "Account Type": "RES",
  },
];


const kpiDataObject = {};

kpi_data.forEach(item => {
  const buId = item["BU ID"];
  kpiDataObject[buId] = item;
});

console.log(kpiDataObject);

