const sql = require("mssql");

async function performBulkInsert() {
  try {
    // Create a connection pool
    const pool = await new sql.ConnectionPool({
      user: "deevia",
      password: "kiran@123",
      server: "deevia-trial.database.windows.net",
      database: "hvac_db",
    }).connect();

    // Define the data you want to bulk insert
    const dataToInsert = [
      { type: [sql.NVarChar], length: 65535, name: "instance_name" },
      { type: [sql.NVarChar], length: 65535, name: "id" },
      { type: [sql.NVarChar], length: 65535, name: "active" },
      { type: [sql.NVarChar], length: 65535, name: "name" },
      { type: [sql.NVarChar], length: 65535, name: "officialName" },
      { type: [sql.NVarChar], length: 65535, name: "email" },
      { type: [sql.NVarChar], length: 65535, name: "currency" },
      { type: [sql.NVarChar], length: 65535, name: "phoneNumber" },
      { type: [sql.NVarChar], length: 65535, name: "invoiceHeader" },
      { type: [sql.NVarChar], length: 65535, name: "invoiceMessage" },
      { type: [sql.NVarChar], length: 65535, name: "defaultTaxRate" },
      {
        type: [sql.NVarChar],
        length: 65535,
        name: "authorizationParagraph",
      },
      {
        type: [sql.NVarChar],
        length: 65535,
        name: "acknowledgementParagraph",
      },
      { type: [sql.NVarChar], length: 65535, name: "address" },
      { type: [sql.NVarChar], length: 65535, name: "addressstreet" },
      { type: [sql.NVarChar], length: 65535, name: "addressunit" },
      { type: [sql.NVarChar], length: 65535, name: "addresscity" },
      { type: [sql.NVarChar], length: 65535, name: "addressstate" },
      { type: [sql.NVarChar], length: 65535, name: "addresszip" },
      { type: [sql.NVarChar], length: 65535, name: "addresscountry" },
      { type: [sql.NVarChar], length: 65535, name: "materialSku" },
      { type: [sql.NVarChar], length: 65535, name: "quickbooksClass" },
      { type: [sql.NVarChar], length: 65535, name: "accountCode" },
      { type: [sql.NVarChar], length: 65535, name: "franchiseId" },
      { type: [sql.NVarChar], length: 65535, name: "conceptCode" },
      {
        type: [sql.NVarChar],
        length: 65535,
        name: "corporateContractNumber",
      },
      { type: [sql.NVarChar], length: 65535, name: "tenant" },
      { type: [sql.NVarChar], length: 65535, name: "tenantid" },
      { type: [sql.NVarChar], length: 65535, name: "tenantname" },
      { type: [sql.NVarChar], length: 65535, name: "tenantaccountCode" },
      { type: [sql.NVarChar], length: 65535, name: "tenantfranchiseId" },
      { type: [sql.NVarChar], length: 65535, name: "tenantconceptCode" },
      { type: [sql.NVarChar], length: 65535, name: "tenantmodifiedOn" },
      { type: [sql.NVarChar], length: 65535, name: "createdOn" },
      { type: [sql.NVarChar], length: 65535, name: "modifiedOn" },
      { type: [sql.NVarChar], length: 65535, name: "externalData" },
    ];

    // Create a table object with the columns you want to insert into
    const table = new sql.Table("SampleTable");
    table.create = true; // Create the table if it doesn't exist

    // Define the columns of the table
    // Define the columns based on the header_data
    dataToInsert.map((column) => {
      table.columns.add(`${column.name}`, sql.NVarChar(sql.MAX)); // Adjust the data type as needed
    });

    // Add the data rows to the table
    table.rows = [
      [
        "Expert Heating and Cooling Co LLC",
        108709,
        true,
        "Imported Default Businessunit",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2022-09-08T16:43:46.7311048Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        1000004,
        true,
        "Imported Businessunit",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2022-09-08T16:43:46.7311048Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        1034876,
        true,
        "10EXP-Resid AOR",
        "Expert Residential AOR",
        "info@expertheatcool.com",
        "USD",
        "(734) 676-4488",
        "Expert Heating and Cooling Co.\n" +
          "24400 Northline Road \n" +
          "Taylor Michigan, 48180\n" +
          "(734) 676-4488",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "24400 Northline Road",
        null,
        "Taylor",
        "MI",
        "48180",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2023-09-19T15:25:31.9133619Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        1034877,
        true,
        "20EXP-Resid NC",
        "Expert Residential New Const",
        "info@expertheatcool.com",
        "USD",
        "(734) 676-4488",
        "Expert Heating and Cooling Co.\n" +
          "24400 Northline Road \n" +
          "Taylor Michigan, 48180\n" +
          "(734) 676-4488",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "24400 Northline Road",
        null,
        "Taylor",
        "MI",
        "48180",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2023-08-04T20:16:45.0733502Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        1034878,
        true,
        "30EXP-Comm AOR",
        "Expert Commercial AOR",
        "ccain@expertheatcool.com",
        "USD",
        "(734) 676-4488",
        "Expert Heating and Cooling Co.\n" +
          "24400 Northline Road \n" +
          "Taylor Michigan, 48180\n" +
          "(734) 676-4488",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "24400 Northline Road",
        null,
        "Taylor",
        "MI",
        "48180",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2023-09-19T15:25:31.9224975Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        1034879,
        true,
        "40EXP-Comm NC",
        "Expert Commercial New Constr",
        "ccain@expertheatcool.com",
        "USD",
        "(734) 676-4488",
        "Expert Heating and Cooling Co.\n" +
          "24400 Northline Road \n" +
          "Taylor Michigan, 48180\n" +
          "(734) 676-4488",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "24400 Northline Road",
        null,
        "Taylor",
        "MI",
        "48180",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2023-08-04T20:17:09.4295114Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        1034880,
        true,
        "50EXP-Resid Service",
        "Expert Residential Service",
        "info@expertheatcool.com",
        "USD",
        "(734) 676-4488",
        "Expert Heating and Cooling Co.\n" +
          "24400 Northline Road \n" +
          "Taylor Michigan, 48180\n" +
          "(734) 676-4488",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "24400 Northline Road",
        null,
        "Taylor",
        "MI",
        "48180",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2023-08-28T15:06:54.6068923Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        1034881,
        true,
        "60EXP-Comm Service",
        "Expert Commercial Service",
        "info@expertheatcool.com",
        "USD",
        "(734) 676-4488",
        "Expert Heating and Cooling Co.\n" +
          "24400 Northline Road \n" +
          "Taylor Michigan, 48180\n" +
          "(734) 676-4488",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "24400 Northline Road",
        null,
        "Taylor",
        "MI",
        "48180",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2023-08-04T20:17:45.3836424Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        1034882,
        true,
        "70EXP-OTC",
        "Expert Over the Counter",
        "pgravlin@expertheatcool.com",
        "USD",
        "(734) 676-4488",
        "Expert Heating and Cooling Co.\n" +
          "24400 Northline Road \n" +
          "Taylor Michigan, 48180\n" +
          "(734) 676-4488",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2023-08-04T20:17:58.203946Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        1034883,
        true,
        "80EXP-Resid Maint",
        "Expert Residential Maintenance",
        "info@expertheatcool.com",
        "USD",
        "(734) 676-4488",
        "Expert Heating and Cooling\n" +
          "24400 Northline Road \n" +
          "Taylor Michigan, 48180\n" +
          "(734) 676-4488",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "24400 Northline Road",
        null,
        "Taylor",
        "MI",
        "48180",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2023-08-29T21:10:26.523387Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        1034884,
        true,
        "90EXP-Comm Maint",
        "Expert Commercial Maintenance",
        "acarlos@expertheatcool.com",
        "USD",
        "(734) 676-4488",
        "Expert Heating and Cooling Co.\n" +
          "24400 Northline Road \n" +
          "Taylor Michigan, 48180\n" +
          "(734) 676-4488",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed by {BusinessUnitOfficialName} has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "24400 Northline Road",
        null,
        "Taylor",
        "MI",
        "48180",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "0001-01-01T00:00:00Z",
        "2023-08-04T20:18:36.88543Z",
        null,
      ],
      
      
      [
        "Expert Heating and Cooling Co LLC",
        55786506,
        true,
        "51EST-Resid Service",
        "Expert Residential Service",
        "info@expertheatcool.com",
        "USD",
        "(313) 822-6633",
        "Expert Heating and Cooling Co.\n" +
          "18139 E 9 Mile Rd.\n" +
          "Eastpointe, MI  48021\n" +
          "(313) 822-6633\n",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "18139 East 9 Mile Road",
        null,
        "Eastpointe",
        "MI",
        "48021",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "2022-09-08T20:20:01.9559007Z",
        "2023-08-04T20:17:34.1781351Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        55793158,
        true,
        "11EST-Resid AOR",
        "Expert Residential AOR",
        "info@expertheatcool.com",
        "USD",
        "(313) 822-6633",
        "Expert Heating and Cooling\n" +
          "18139 E 9 Mile Rd.\n" +
          "Eastpointe, MI  48021\n" +
          "313-822-6633",
        "Thank you for choosing Expert Heating and Cooling",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work performed by Expert Heating & Cooling has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "18139 E 9 Mile Rd.",
        null,
        "Eastpointe",
        "Michigan",
        "48021",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "2022-09-08T20:03:02.8581213Z",
        "2023-09-19T15:25:31.9225607Z",
        null,
      ],
      [
        "Expert Heating and Cooling Co LLC",
        55794188,
        true,
        "81EST-Resid Maint",
        "Expert Residential Maintenance",
        "info@expertheatcool.com",
        "USD",
        "(313) 822-6633",
        "Expert Heating and Cooling\n" +
          "18139 E 9 Mile Rd.\n" +
          "Eastpointe, MI  48021\n" +
          "(313) 822-6633",
        "Thank you for choosing Expert Heating and Cooling\n" +
          "Not just a name... it's the truth!",
        null,
        "This invoice is agreed and acknowledged.  Payment is due upon receipt.  A service fee will be charged for any returned checks, and a finance charge of 1% per month may be applied for overdue amounts.",
        "I find and agree that all work has been completed in a satisfactory and workmanlike manner. I have been given the opportunity to address concerns and/or discrepancies in the work provided, and I either have no such concerns or have found no discrepancies or they have been addressed to my satisfaction. My signature here signifies my full and final acceptance of all work performed by the contractor.",
        null,
        "18139 East 9 Mile Road",
        null,
        "Eastpointe",
        "MI",
        "48021",
        "USA",
        null,
        null,
        null,
        null,
        "NotSet",
        null,
        null,
        1011756844,
        "expertheatingcoolingco",
        null,
        null,
        "NotSet",
        "2023-08-17T07:24:46.577985Z",
        "2022-09-08T20:30:37.877767Z",
        "2023-08-04T20:18:22.4834244Z",
        null,
      ],
    ];

    // Bulk insert the data into the table
    // const request = new sql.Request(pool);
    // const result = await request.bulk(table);

    // Execute the bulk insert
    await pool.request().bulk(table);

    console.log("Bulk insert result:", result);

    // Close the connection pool
    await pool.close();
  } catch (err) {
    console.error("Error performing bulk insert:", err);
  }
}

// Call the function to perform the bulk insert
performBulkInsert();
